### ISSUE TITLE
Bad link for "learn how to change the storage class."

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#117]
Page: [What’s new in Cloud Manager 3.6](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

"learn how to change the storage class." links to a localhost address.
http://localhost:4001/occm/us-en/task_tiering.html#changing-the-tiering-level

**Comment by netapp-bcammett** [comment]
Thank you for catching this issue! It has been fixed.
