### ISSUE TITLE
Missing URLs required for Cloud Manager access

### ISSUE THREAD

**Issue by ashley-leask** [NetAppDocs/occm#123]
- [ ] Page:

 [Networking requirements for Cloud Manager](https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html)

Customer deploying OCCM in Azure has notified me that they were required to add the following URLs to their security config before access to the Cloud Mgr system would function correctly.

cdn.auth0.com
widget.intercom.io

**Comment by netapp-bcammett** [comment]
Thank you for providing this feedback. I added the two URLs, as shown below:

![image](https://user-images.githubusercontent.com/18287750/54287503-24f7ed80-457c-11e9-9868-ce3cc7ae9062.png)

Please let us know if any further changes are required. Thanks again for your feedback.
