### ISSUE TITLE
mysupport.netapp.com. is an incorrect address

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/occm#138]
Page: [Networking requirements for Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/reference_networking_aws.html)

mysupport.netapp.com. is an incorrect address

should be the following 2 urls we use for Autosupoprt traffic. 

https://support.netapp.com/aods/asupmessage
support.netapp.com/asupprod/post/1.0/postAsup

thank you

**Comment by netapp-bcammett** [comment]
Thank you for your feedback.

I removed mysupport.netapp.com and replaced it with the two URLs that you provided.

I made this change on two other pages, as well: "Networking requirements for Cloud Volumes ONTAP in Azure" and "Networking requirements for Cloud Manager."

Thanks again,
Ben
