### ISSUE TITLE
When changing to a different language, have the language name in the specified language

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/occm#165]
Page: [Cloud Manager and Cloud Volumes ONTAP documentation](https://docs.netapp.com/us-en/occm/index.html)

(I'm an English reader) - when I change from English to Japanese, it changes the language selection menu to the specified language as well. It would be great if this menu could be in the language that we are specifying, i.e. English is 'English' even though it is '英語' in Japanese.

**Comment by akseldavis** [comment]
Thanks Phoebe. We're working on an override for the language selector and this would be solved by that implementation. I will share dates internally once determined.

**Comment by phoebegoh** [comment]
Thank you! Your turnaround is incredible. Love your work!

________________________________

**Comment by akseldavis** [comment]
Hi Phoebe, your request was implemented in late September. Thanks for the great suggestion, and let me know if it doesn't meet your expectations.
