### ISSUE TITLE
Add link to CVO on AWS course:

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#167]
Page: [Where to get help and find more information](https://docs.netapp.com/us-en/occm/reference_additional_info.html)

**Comment by nichollri** [comment]
COURSE NAME: Cloud Volumes ONTAP Deployment and Management for AWS
ENROLLMENT LINK: https://learningcenter.netapp.com/LC?ObjectType=WBT&ObjectID=00376094

**Comment by netapp-bcammett** [comment]
Done! Thank you for requesting the change.

![image](https://user-images.githubusercontent.com/18287750/60191592-92b1e780-9802-11e9-8b05-2d83d85925cb.png)
