### ISSUE TITLE
access denied on document link

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#172]
Page: [Networking requirements for Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/reference_networking_aws.html)

https://s3.amazonaws.com/quickstart-reference/microsoft/activedirectory/latest/doc/Microsoft_Active_Directory_Quick_Start.pdf

**Comment by netapp-bcammett** [comment]
It looks like AWS migrated the PDF to the core AWS documentation:
https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/welcome.html
I'll update the link in the docs.
Thank you for catching this!
