### ISSUE TITLE
Add a note on the possible use of NVMe disks

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/occm#174]
Page: [Disks and aggregates](https://docs.netapp.com/us-en/occm/concept_storage.html)

Currently there's an info note on this:

* Cold HDD disks are not supported with HA configurations and with data tiering.

It'd be nice to add a note on NVMe to that:

- Cold HDD disks are not supported with HA configurations and with data tiering.
- NVMe disks are supported only as [FlashCache](https://docs.netapp.com/us-en/occm/task_enabling_flash_cache.html).

**Comment by netapp-bcammett** [comment]
Good suggestion. My apologies on the delay in response, as I was away for the US holiday.

Note that the specific EC2 instance types that include local NVMe storage is called out in the Cloud Volumes ONTAP Release Notes:
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_96.html

I'll update the Cloud Manager page that you referenced to also link to that page in the Cloud Volumes ONTAP Release Notes.

**Comment by netapp-bcammett** [comment]
The page was updated based on your feedback. Thanks again!
