### ISSUE TITLE
VNet service endpoint IS required.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#175]
Page: [Networking requirements for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/reference_networking_azure.html)

I was talking to Yuval about this section of the documentation and he indicated that a service endpoint IS required.   And that this documentation part is wrong. 

Yuval - "You must go through the as a direct service endpoint in your VNet 
I’m not sure what the documentation says otherwise."

**Comment by netapp-bcammett** [comment]
The page was updated to more directly state that you don't need to create a VNet service endpoint yourself because Cloud Manager will do it for you (if you gave Cloud Manager the required permissions).

Thanks for your feedback!
