### ISSUE TITLE
Changes to backup functionality / Addition of Cloud Manager Settings

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/occm#176]
Hi Ben!  Hope all is well for you.  

Is it possible to add any information about the removal of the OCCM Backup functionality?  My customer was wondering where it went and there doesn't seem to be anything documenting that change (that I've found at least).  According to Akash it is due to OCCM behaving more like SaaS, but I haven't seen anything 'official'.

Can the information on the below-linked page be added to the main OCCM documentation?  It took me a while to locate info on what these settings actually control.
https://library.netapp.com/ecmdocs/ECMLP2484727/html/GUID-1B0AA9CB-0662-4FE6-A459-DD64E09063B6.html

Please let me know if you have questions-
Steve

**Comment by netapp-bcammett** [comment]
Hi Steve,

Yes, I'm working on documentation updates for restoring Cloud Manager based on the recent changes. I'll let you know as soon as it's ready.

**Comment by netapp-bcammett** [comment]
These doc updates were taken care of. Thanks again, Steve!
