### ISSUE TITLE
Dedupe across volumes not supported

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#190]
Page: [Known limitations](https://docs.netapp.com/us-en/occm/reference_limitations.html)

A customer asked if CVO supported cross volume deduplication (e.g. aggregate dedupe).
I looked here to see if it was unsupported, and didn't see it as unsupported.  Just about that time Yuval Kalderon indicated that it is not supported in CVO.  Not sure if this page is supposed to have every feature not supported, but thought I would highlight it.

**Comment by netapp-bcammett** [comment]
Hi Richard,

Is that the same thing as "Aggregate-level inline deduplication"? That's listed in the Cloud Volume ONTAP Release Notes as an unsupported feature:

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_96.html#unsupported-ontap-features

**Comment by nichollri** [comment]
Inline is different since it happens while the blocks are being processed.  ONTAP also supports background aggregate deduplication: https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-vsmg%2FGUID-D48229EA-6C7A-4497-8B09-5757839618BF.html

Now I am questioning which the customer was asking about and which Yuval was answering about.  I'll get back to you.

**Comment by netapp-bcammett** [comment]
Added "aggregate-level background deduplication" to the list of unsupported features:
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_96.html#unsupported-ontap-features
