### ISSUE TITLE
be more precise on enable interoperability access?

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#202]
Page: [Getting started with Cloud Volumes ONTAP in Google Cloud Platform](https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html)

I assume we are enabling it for the Google Project where CVO will be deployed.

![image](https://user-images.githubusercontent.com/519212/65355013-f0b25900-dbbe-11e9-879c-7e5a9b8347a5.png)
![image](https://user-images.githubusercontent.com/519212/65355086-1f303400-dbbf-11e9-8ff1-871e5bd275f8.png)

I assume this is what I needed to do (attached before and after images) because I didn't see any generic interoperability enable setting.

**Comment by netapp-bcammett** [comment]
Thanks for the feedback. I made changes and published the updates.

https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html
