### ISSUE TITLE
Add note about using YAML to create a custom role

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#203]
Page: [Getting started with Cloud Volumes ONTAP in Google Cloud Platform](https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html)

In step 4, where you say make sure the user has these permissions.  The link is a YAML file.  If you want to create a custom role to be sure that your user has all those permissions then you can only do that currently via the gcloud command line.  I thought it might be worth mentioning.

You could even say to ensure you have these permissions you can create a custom role using this YAML file and then attach it to your user.  

![image](https://user-images.githubusercontent.com/519212/65356607-d4182000-dbc2-11e9-9a04-9c6d9a03e2ee.png)

**Comment by netapp-bcammett** [comment]
Thanks again. I made changes and published the updates.

https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html
