### ISSUE TITLE
Missing an API in the "Enable Google Cloud APIs"  section in the documentation

### ISSUE THREAD

**Issue by banusundhar** [NetAppDocs/occm#209]
The documentation here: https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html lists only 3 APIs to be enabled. I had to enable a fourth one "Cloud Resource Manager API" for CVO deployment.

Cloud Deployment Manager V2 API
Compute Engine API
Stackdriver Logging API
Cloud Resource Manager API ----------------> Add this one in the doc please.

**Comment by netapp-bcammett** [comment]
Hi Banu,

Thank you for making us aware of this requirement. I updated the page to include "Cloud Resource Manager API."

Thank you for helping us ensure the quality of the docs.

Regards,
Ben
