### ISSUE TITLE
NetApp Doc

### ISSUE THREAD

**Issue by gopinath147** [NetAppDocs/occm#215]
Page: [Cloud Manager and Cloud Volumes ONTAP documentation](https://docs.netapp.com/us-en/occm/index.html)

**Comment by netapp-bcammett** [comment]
Hi there,

I don't see any text in the issue that you opened. Can you please let me know if there's a change that you'd like to see in the docs?

Thank you for your help.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I'm going to go ahead and close this issue. Please open a new issue if you have any feedback for the documentation. Thanks!
