### ISSUE TITLE
Step reference confusing in Step 4

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#218]
Page: [Getting started with Cloud Volumes ONTAP in Google Cloud Platform](https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html)

"You’ll associate this service account with the Cloud Manager VM in step 5."

But step 5 is  Subscribe from Marketplace

**Comment by netapp-bcammett** [comment]
😕 
Fixed! Thank you! I missed updating that reference when we added a step for the GCP Marketplace.
