### ISSUE TITLE
Further clarification on free space requirement

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/occm#221]
Page: [Cloud Manager host requirements](https://docs.netapp.com/us-en/occm/reference_cloud_mgr_reqs.html)

Instead of saying that the Free Space requirement is "50 GB" is it possible to instead say that XX GB of space is required, for example, in the /opt directory?  

Please let me know if this is not clear.

Thanks,
Steve

**Comment by definitelynotsteve** [comment]
Here is an example from our NSLM installation guide that does a great job (IMO) in detailing the space requirement on a per-directory basis.  https://library.netapp.com/ecm/ecm_get_file/ECMLP2856325 See the table on page 6 under the heading "Hardware and virtual system requirements".  Thanks, Steve

**Comment by netapp-bcammett** [comment]
Thank you for the feedback, Steve. I'll check with our engineers, let you know what I find, and make the required doc updates.

**Comment by netapp-bcammett** [comment]
The docs were updated last month to indicate that 100 GB is needed in /opt.

Thanks again for your feedback!
