### ISSUE TITLE
Port 10000 is not required for SnapMirror

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#244]
Page: [Replicating data between systems](https://docs.netapp.com/us-en/occm/task_replicating_data.html)

The text mentions port 10000 being required, but port 10000 is for NDMP and therefore not required for SnapMirror.

**Comment by netapp-bcammett** [comment]
Hi Richard,

Port 10000 is listed in the ONTAP documentation as required for cluster peering:

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-csp/GUID-729E6FCF-9640-47B8-8C20-EC0B89F8129B.html

Regards,
Ben

**Comment by netapp-bcammett** [comment]
The team verified that port 10000 isn't required for data replication, so it was removed from the docs.
