### ISSUE TITLE
Step 3 adding role is a bit confusing.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#249]
Page: [Getting started with Cloud Volumes ONTAP in Google Cloud Platform](https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html)

In this section right step 3 here:

_**Grant the Cloud Manager service account with access to this tiering service account by providing the Service Account User role.**

You can provide the user role in step 3 of the wizard when you create the tiering service account, or grant the role after the service account was created.

You’ll need to select the tiering service account later when you create a Cloud Volumes ONTAP working environment. This tiering service account is different from the Cloud Manager service account that you created in step 2._

The bolded part is confusing about if you are adding the Storage Admin service account as a service account user to Cloud Manager service account.  Or vice-versa where you add the Cloud Manager service account as a service account user to the Storage Admin service account.

From engineering I got this:
Add the Cloud Manager service account as a "service account user" to the Storage Admin service account.  

This seems like a much more straightforward way to state it. Both myself and a customer interpreted what is currently written, the opposite way.

**Comment by netapp-bcammett** [comment]
Hi Richard,

Thanks for the feedback. Can you explain what you mean by "Storage Admin service account"?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I updated the page as we discussed.

Thanks again!
