### ISSUE TITLE
Update lead

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/occm#254]
Page: [Installing Cloud Manager in an Azure Germany region](https://docs.netapp.com/us-en/occm/task_installing_azure_germany.html)

Hi Ben, 
I was using your docs for guidance for CSA. I noticed that the lead sentence explains that Cloud Manager is not available in Germany, but the After you finish section explains that it is available. It may need an update.

**Comment by netapp-bcammett** [comment]
Hi Rachel,

Thank you for providing your feedback. This is a bit of an oddity. Users normally deploy software in the cloud from the cloud provider's marketplace. For Azure, there is no marketplace in the Germany region, but you can still use Cloud Manager and Cloud Volumes ONTAP in that region. You just need to manually download the installer and then install the software on an existing Linux host running in the Germany region.

**Comment by netapp-bcammett** [comment]
Your feedback was incorporated. Thanks again!
