### ISSUE TITLE
For new Cloud Backup we no longer need Private Links

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#256]
Page: [What’s new in Cloud Manager 3.8](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

This statement is misleading: "Cloud Manager no longer needs to set up interface VPC endpoints to the Backup to S3 service."

We no longer need private links to the Backup to S3 service.
And while a private link could be considered a VPC endpoint in a general sense.
I think may people would read this statement as we no longer need an endpoint to S3.   We do still need an endpoint to S3 for the data traffic (same endpoint that we use for FabricPool).  I think it would be more clear to change this sentence to say we no longer need private links to the Backup to S3 service.

This is the AWS page on the Private link: https://docs.aws.amazon.com/vpc/latest/userguide/endpoint-service.html
that the old CBS service required.

**Comment by netapp-bcammett** [comment]
Fixed! Thank you for the feedback.

![image](https://user-images.githubusercontent.com/18287750/76096340-ec72d000-5f93-11ea-9202-953969639d62.png)
