### ISSUE TITLE
How to see the status of a backup

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#260]
Page: [Backing up data to Amazon S3](https://docs.netapp.com/us-en/occm/task_backup_to_s3.html)

Hi, supposing some Volumes first backup may take long time to complete...

Please consider to add a section on how to verify the progress of currently running backups.

Regards,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for providing your feedback. I've forwarded your question on to the product team. I'll let you know what I hear.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Cloud Manager doesn't currently verify the status of an in-progress backup. I have passed your feedback on to product management.

Regards,
Ben
