### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by chrismaki** [NetAppDocs/occm#264]
Page: [Licensing](https://docs.netapp.com/us-en/occm/concept_licensing.html)

Needs clarification on what happens when an existing license runs out before being renewed properly. This page makes it sound as though you have a 30 day grace period, but that is not the case from what I understand.

**Comment by netapp-bcammett** [comment]
Hi Chris,

Thank you for providing your feedback. The following sentence is near the the end of the "License expiration" section:

If you do not renew the license in time, the Cloud Volumes ONTAP system shuts itself down. If you restart it, it shuts itself down again.

Maybe that sentence should be moved under the "License renewal" section?

Which part makes it sound like there's a 30-day grace period? The License Expiration section does mention the 30-day warning that appears in Cloud Manager.

Thanks again for your feedback.

Regards,
Ben

**Comment by chrismaki** [comment]
Hi Ben,

The second sentence that states:

_If an active license is not installed, the Cloud Volumes ONTAP system shuts itself down after 30 days._

If I had an active license for a year, on day 366 it becomes inactive, this line makes it sound like I should get 30 days grace.

Cheers,
-Chris

**Comment by netapp-bcammett** [comment]
Got it. That makes sense. I'll work on the updates and get back to you.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Chris,

I updated the page by removing that statement. It was misleading, as you said. Please take a look and let me know if you think any further changes are required.

https://docs.netapp.com/us-en/occm/concept_licensing.html

Thanks again,
Ben
