### ISSUE TITLE
Changing write speed to normal or high

### ISSUE THREAD

**Issue by sanjeshu** [NetAppDocs/occm#270]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

We need to remove this line from the doc 

**For HA pairs, the change is nondisruptive. HA pairs continue to serve data.**

**Comment by netapp-bcammett** [comment]
Thank you for submitting this issue. I updated the section to clarify that the setting is for single node systems only. That includes removing the line that you mentioned.

https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html#changing-write-speed-to-normal-or-high

Thanks again for submitting your feedback and making the docs better!

Regards,
Ben
