### ISSUE TITLE
Permissions Page

### ISSUE THREAD

**Issue by ezrahill** [NetAppDocs/occm#272]
The **How Cloud Manager uses cloud provider permissions** page seem to be out of date and doesn't reflect the permissions granted within the NetApp provided policies.  I can only speak of AWS.

**Page**
https://docs.netapp.com/us-en/occm/reference_permissions.html#what-cloud-manager-does-with-aws-permissions

**Policies**
https://occm-sample-policies.s3.amazonaws.com/Policy_for_Cloud_Manager_3.8.2.json

**Comment by netapp-bcammett** [comment]
Hi Ezra,

Thank you for your feedback. I've compared what's in the docs vs. what's in the policy and I see that the following permissions aren't listed in the docs:

                "kms:ReEncrypt*",
                "kms:CreateGrant",
                "ec2:DescribeVpcEndpoints",
                "ec2:CreateVpcEndpoint",
                "ec2:ModifyVpcEndpoint",
                "ec2:DeleteVpcEndpoints"

Does that match the discrepancies that you found?

I'll add the first two "kms" permissions to the docs.

The four "VpcEndpoint" permissions are actually no longer used by Cloud Manager. I contacted the person who manages the policy file and he will be removing them.

After that, the two should be in sync.

Let me know if you have any additional feedback.

Thanks again,
Ben

**Comment by ezrahill** [comment]
That checks out, thanks for addressing.

**Comment by netapp-bcammett** [comment]
The two "kms" permissions were added to the docs. I'll keep this open until the "VpcEndpoint" permissions are removed from the policy.

**Comment by netapp-bcammett** [comment]
The "VpcEndpoint" permissions were officially removed in the latest policy:
https://occm-sample-policies.s3.amazonaws.com/Policy_for_Cloud_Manager_3.8.7.json

Thanks,
Ben
