### ISSUE TITLE
Suggestion: At top of page, differentiate different Azure account and different subscription.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#278]
Page: [Setting up and adding Azure accounts to Cloud Manager](https://docs.netapp.com/us-en/occm/task_adding_azure_accounts.html)

There are two main parts to this page, the first part is how to add a completely separate Azure account to Cloud Manager.  The second part is how within the same Azure account to associate another Azure subscription.  I would think it would be nice at the top of the page to differentiate between these two, so it would be easier for people to understand the difference and just jump to the bottom for the adding another subscription.

**Comment by netapp-bcammett** [comment]
Good suggestion, RIchard. I've drafted up the following changes. Let me know if you think any additional changes are required.

"There are two ways to manage Azure accounts in Cloud Manager. First, if you want to deploy Cloud Volumes ONTAP in different Azure accounts, then you need to provide the required permissions and add the credentials to Cloud Manager. The second way is to associate additional subscriptions with the Azure managed identity."

**Comment by netapp-bcammett** [comment]
Your feedback was incorporated. Thanks again!
