### ISSUE TITLE
Link to Cloud Manager in Azure Marketplace is not working.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#283]
Page: [Deploying Cloud Manager from the Azure Marketplace](https://docs.netapp.com/us-en/occm/task_launching_azure_mktp.html)

I click on the link in Step 1 and I get a 404 page not found.

**Comment by netapp-bcammett** [comment]
Thank you for letting me know. Looks like Azure changed the links to the Marketplace. It's updated now.
