### ISSUE TITLE
Describe how Cloud Manager rotates the keys

### ISSUE THREAD

**Issue by pascaldewild** [NetAppDocs/occm#299]
Page: [Adding AWS credentials and subscriptions in Cloud Manager](https://docs.netapp.com/us-en/occm/task_adding_aws_accounts.html)

When in a discussion about the rotation of Access Keys in AWS, Aviv suggested to use an Instance Profile instead, as Cloud Manager would then rotate the keys automatically. However, I cannot find this in the documentation, so can we add this please? Not sure if this is the correct page (I think it is though). 

Maybe even include a best practice where we would advise keys and where we would advise 'assume role' would be great!

Thanks already!

**Comment by netapp-bcammett** [comment]
Thank you for providing this feedback. I've reached out to Aviv to learn more. I need to learn from him before I can add the information to the docs.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hello,

After discussing with Aviv, I updated the page to describe how to securely rotate AWS credentials. You can find the information here: https://docs.netapp.com/us-en/occm/task_adding_aws_accounts.html

I also added it to the conceptual page that describes how Cloud Manager uses credentials and permissions:
https://docs.netapp.com/us-en/occm/concept_accounts_aws.html

Thanks again for providing this feedback!

Regards,
Ben
