### ISSUE TITLE
Firewall Support for Storage Accounts in Azure.

### ISSUE THREAD

**Issue by sanjeshu** [NetAppDocs/occm#312]
Page: [Security group rules for Azure](https://docs.netapp.com/us-en/occm/reference_security_groups_azure.html)

Can we please add a section on whether we support firewall on storage account in Azure.

A customer came to us asking this question.

* We would like to apply firewall on Azure netapp CVO storage account. Will it cause any problem? Is it supported by netapp? Currently our security team enabled ATP (advance threat protection) on netapp cvo storage account, which is quite expensive, and not really needed for us, but we need to protect somehow the storage account. *

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for providing this feedback. I've reached out to our product team to find the answer to the question. I'll let you know when I hear more and I'll update the docs accordingly.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hello,

Sorry for the delay. I heard back from the product team:

"If you need to provide an additional layer of security, we recommend applying private links/endpoints to the Azure storage account using a custom Cloud Manager configuration. To learn more, contact the cloud team by using the in-product chat."

Please let me know if you have any additional questions.

Regards,
Ben
