### ISSUE TITLE
Can we add 'known limitations'?

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/occm#313]
Page: [Evaluating](https://docs.netapp.com/us-en/occm/concept_evaluating.html)

- Can we add "Evaluation licenses do not allow Data ONTAP upgrades."
- And any other limitations known to eval licenses.

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for providing your feedback. I've sent some questions off to the product management team so I can address this request. I'll follow up when I hear back.

Thanks,
Ben

**Comment by jenatnetapp** [comment]
Hey Ben, 

Did product management ever get back to you on this?

Jennifer

**Comment by netapp-bcammett** [comment]
I'm trying to get one last piece of information. I'll follow up on that.

**Comment by netapp-bcammett** [comment]
Hi @randobrando46, 

After a bit of back and forth, I was able to update the Evaluating page to include full descriptions of both 30-day free PAYGO trials and evaluation licenses (BYOL). You can see the updates here: https://docs.netapp.com/us-en/occm/concept_evaluating.html

The page includes any known limitations, such as the one that you outlined about not allowing upgrades.

Thank you for your providing your feedback and helping us make the docs better!
