### ISSUE TITLE
Modifying the storage virtual machine name

### ISSUE THREAD

**Issue by rbenigno** [NetAppDocs/occm#317]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

Section: **Modifying the storage virtual machine name**

We are no longer able to find the option to edit an SVM name as described in the docs.  Can we just rename on the cluster or does something need to happen in Cloud Manager to rename?

Thank you!

**Comment by netapp-bcammett** [comment]
Hi Ryan,

You should still be able to edit the SVM name from the Information page. But the name of the field did change, as shown below (I'll update the docs).

![image](https://user-images.githubusercontent.com/18287750/87027116-b005e980-c1aa-11ea-9fb6-c4b9af9e1690.png)

Can you confirm that you don't see the "Storage VM Name" field with the edit icon?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
How many SVMs does the working environment have?

**Comment by rbenigno** [comment]
Checked that area multiple times and did not see the SVM with an edit button.  Did not grab a screen shot, so it's possible we missed it.

We have two SVMs in this customer's working environment.  I was getting set to power on a lab specifically to see multiple SVMs was a factor, but it sounds like you may already be going down that path.

Thank you!

**Comment by netapp-bcammett** [comment]
I confirmed that Cloud Manager doesn't allow you to edit an SVM name if there are multiple SVMs. You can change the SVM name directly from the cluster.

I'll go ahead and update the docs with that information.

Thanks for catching this and opening the issue.

Regards,
Ben

**Comment by rbenigno** [comment]
Thank you!
