### ISSUE TITLE
Please add a proper description how the subscription must be formated

### ISSUE THREAD

**Issue by trulleberg** [NetAppDocs/occm#320]
Page: [Getting started with Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/task_getting_started_azure.html)

Please add an example like:

"/subscriptions/d333af45-0d07-4154-943d-c25fbzzzzzzz",

We stumbled on the /subscriptions/ for a long time :D

**Comment by netapp-bcammett** [comment]
Great suggestion! I updated the page with an example.

Thank you for taking the time to file this issue. Please let me know if you have any additional feedback in the future.

Thanks again,
Ben
