### ISSUE TITLE
misleading statement

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#326]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

I was working with a customer (Tableau) who swore that our documentation said that they could easily switch between Pay-Go and BYOL.  Whereas we know that (as of now) it is a procedure where you have to spin up a new CVO system and snapmirror data over.  They were quite upset when they found out that it was snapmirror and a cutover outage.
Anyway I was surprised by their misunderstanding but then when I saw how they read this line, I understood their confusion.

For example, **you can change between pay-as-you-go configurations**, change the instance or VM type, and **move to an alternate subscription**.

And then right below it has the process for updating BYOL license, so based on the statement above they thought they could just enter the license file using those steps and Pay Go would change to BYOL.  When reading it with them and the placement of the next heading I definitely understood how they could have been confused.

I am not 100% sure how we can change this wording smoothly, "change tiers?levels? within a pay-go subscription model".
Maybe a statement that switching between Pay-Go and BYOL at this point in time requires a data move between CVO systems?

**Comment by netapp-bcammett** [comment]
Hi Richard,

Thank you for submitting this feedback. I changed the intro sentence for this page as follows:

"You might need to change the configuration of Cloud Volumes ONTAP systems as your storage needs change. For example, you can change between pay-as-you-go configurations, change the instance or VM type, and more."

In other words, I removed the part about moving to an alternate subscription. This intro sentence is a summary of the page contents.

Note that the steps on this page explicitly state how to switch from PAYGO to BYOL:

"If you want to switch between a pay-as-you-go subscription and a BYOL subscription or between a single Cloud Volumes ONTAP system and an HA pair, then you need to deploy a new system and then replicate data from the existing system to the new system."

Also note that the Cloud Volumes ONTAP Release Notes includes the following statement:

"Conversions from PAYGO to BYOL aren’t currently supported."

Thanks, 
Ben

**Comment by nichollri** [comment]
Thanks Ben. That sounds good.
