### ISSUE TITLE
Incorrect links for Cloud Manager Policies

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#329]
Page: [Deploying Cloud Manager in an Azure US Government region](https://docs.netapp.com/us-en/occm/task_installing_azure_gov.html)

The broken links are not in this page itself but are in the linked page to:
https://mysupport.netapp.com/site/info/cloud-manager-policies

Within that page there is a section labeled "Jump to the section for your cloud provider"

The links for each cloud provider in that section are broken.  For example Azure is linked here:
https://mysupport.netapp.com/site/#azure

The correct link would be:
https://mysupport.netapp.com/site/info/cloud-manager-policies#azure

**Comment by netapp-bcammett** [comment]
Thank you for opening this issue. We'll get those links fixed!

**Comment by netapp-bcammett** [comment]
The links have been fixed. Thanks again for submitting your feedback.
