### ISSUE TITLE
Azure portal changed for launching Cloud Manager VM

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#33]
![image](https://user-images.githubusercontent.com/519212/39581024-a3032da4-4eb8-11e8-8019-dc579388a900.png)

The line highlighted in red is no longer completely accurate, there is a new security group toggle Basic | Advanced.  The user has to click Advanced to have the CloudManager-nsg selected.

Before clicking Advanced:

![image](https://user-images.githubusercontent.com/519212/39581205-074330c0-4eb9-11e8-9f6e-c04cf65bbf8f.png)

After clicking Advanced:

![image](https://user-images.githubusercontent.com/519212/39581223-1116e40c-4eb9-11e8-8550-57ae25818b7e.png)

**Comment by netapp-bcammett** [comment]
Thank you for the feedback. I updated this section to refer to the Basic and Advanced options.
