### ISSUE TITLE
Terminology in "Global File Cache components" could be more consistent

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/occm#336]
Page: [Learn about Global File Cache](https://docs.netapp.com/us-en/occm/concept_gfc.html)

The language in the text and the graphic could be better aligned. The three components named in the bullets above the graphic are not mentioned anywhere in the graphic.

**Comment by netapp-tonacki** [comment]
Hi Adam,  Thanks for the comment.  I'll get the graphic updated so Edge and Core instances/VMs are more obvious.

**Comment by netapp-tonacki** [comment]
I updated the graphic so that it uses the term "Edge" twice and "Core" once instead of just "SW" in 3 places.   The Management Server is not pictured in this diagram, so I didnot add/update this term in the graphic.

**Comment by adamn-ntap** [comment]
Thank you, Tom.
