### ISSUE TITLE
Reference to .emltpl file could be clarified

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/occm#338]
Page: [End-user training](https://docs.netapp.com/us-en/occm/concept_gfc_enduser_training.html)

Reference to .emltpl file. On a Windows machine, this file extension does not appear to have a default program association. If this is Mac-only, recommend you say as much and/or provide a Windows equivalent.

**Comment by netapp-tonacki** [comment]
Hey Adam,  Thanks for the comment.  I will get a Windows template file and post that.

**Comment by netapp-tonacki** [comment]
I added a .msg Windows template file to this topic.  thanks

**Comment by adamn-ntap** [comment]
Thanks, Tom
