### ISSUE TITLE
Documentation for Azure Tags is misleading

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#351]
Page: [Launching Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/task_deploying_otc_azure.html)

On this page the following is written for Azure Tags:
"Tags are metadata for your Azure resources. Cloud Manager adds the tags to the Cloud Volumes ONTAP system and each Azure resource associated with the system."

This makes it sound like the actual CVO VM object and other associated objects are tagged.  That is not what actually happens.  The only thing that is tagged is the Resource Group object itself that is created when a CVO instance is created.

**Comment by netapp-bcammett** [comment]
Good catch and thanks for submitting this feedback.

The page has been updated. It now says the following:

"Tags are metadata for your Azure resources. When you enter tags in this field, Cloud Manager adds them to the resource group associated with the Cloud Volumes ONTAP system."

Thanks again,
Ben
