### ISSUE TITLE
CLI command being translated

### ISSUE THREAD

**Issue by akseldavis** [NetAppDocs/occm#366]
Page: [Creating a Connector in Azure from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html#setting-up-azure-permissions-to-create-a-connector)

Can we switch `az role definition create...` command to codeblock to prevent translation?

**Comment by netapp-bcammett** [comment]
Aksel,

This has been fixed.

Thanks,
Ben
