### ISSUE TITLE
Azure CVO HA default disk config change

### ISSUE THREAD

**Issue by takehirs** [NetAppDocs/occm#375]
Page: [Default configuration for Cloud Volumes ONTAP](https://docs.netapp.com/ja-jp/occm/reference_default_configs.html)

I found Azure CVO HA default disk config change.Please verify below details.

Before:Azure (HA pairs)
    Two 90 GB Premium SSD disks for the boot volume (one per node)
    Two 140 GB Premium Storage page blobs for the root volume (one per node)
    Two 128 GB Standard HDD disks for saving cores (one per node)
    One Azure snapshot for each boot disk and root disk

After:Azure  (HA pairs)
Change->    Two **10 GB** Premium SSD disks for the boot volume (one per node)
                   Two 140 GB Premium Storage page blobs for the root volume (one per node)
Change->    Two **1024 GB** Standard HDD disks for saving cores (one per node)
Add->         **Two 128 GB Premium SSD disks for the nvram volume (one per node)**
                   One Azure snapshot for each boot disk and root disk

Best Regards,
Shimura.

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for your feedback. Can you please let me know if you found these changes in an internal NetApp build, or from a public build of Cloud Volumes ONTAP?

I've also reached out to our internal engineering team to confirm.

Thank you for submitting this feedback.

Regards,
Ben

**Comment by takehirs** [comment]
Hi Ben-san,
Thnak you for your support.
This change was found in the public build(Azure) of CVO.

Best Regards,
Shimura.

**Comment by netapp-bcammett** [comment]
Hi again,

I made the required changes to the docs:
https://docs.netapp.com/ja-jp/occm/reference_default_configs.html#azure-ha-pairs

Thanks again for reaching out with your feedback.

Regards,
Ben
