### ISSUE TITLE
Request for clarity.

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#381]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

Hi,

In this page, it says changing the instance or machine type for Cloud Volumes ONTAP is non disruptive for HA pair config.
It says "For HA pairs, the change is nondisruptive. HA pairs continue to serve data."

Not sure if this true for SMB/CIFS protocol. Appreciate if someone can review this and clarify in the doc.

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting your question. I've sent it off to my contacts on the product team for confirmation. I'll let you know when I hear back.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Hi again,

I wanted to provide an update based on what I've learned:

> Cloud Manager gracefully updates one node at a time doing takeover and waiting for give back. 
> 
> We've tested both writing and reading files during this process. As connections change, we do see retries on the I/O level, but from the application layer, it overcomes this short “re-wire” of NFS/CIFS connections.
> 
> So as we test it on the client side, we do not see any issues, so it really is a matter of client application and re-try mechanism.

I can summarize this in the docs, in the hopes of providing clarity.

Thanks,
Ben

**Comment by sabarig84** [comment]
Thanks Ben. yes i think it will be better to bring that clarity to the doc page.. appreciate your help.

**Comment by netapp-bcammett** [comment]
I updated the docs to include a summary of what was previously mentioned in this issue.

https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html#changing-the-instance-or-machine-type-for-cloud-volumes-ontap
