### ISSUE TITLE
Formatting Error

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#393]
Page: [How Cloud Manager uses cloud provider permissions](https://docs.netapp.com/us-en/occm/reference_permissions.html)

There is a formatting error on this page for the Azure Permissions - "Microsoft.Resources/deployments/operationStatuses/read". Some of the permissions ended up on the right column, and the description ended up on the left column.

![image](https://user-images.githubusercontent.com/33675510/96266063-37c27780-0f94-11eb-859d-c092818788b3.png)

**Comment by netapp-bcammett** [comment]
Thank you! Checking in the fix now

**Comment by netapp-bcammett** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/18287750/96270259-65f68600-0f99-11eb-814f-370aed9f5b70.png)

Thanks again!
