### ISSUE TITLE
Product names are translated

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/occm#412]
Page: [Cloud Manager and Cloud Volumes ONTAP documentation](https://docs.netapp.com/ja-jp/occm/index.html)

The following product names are localized into Japanese. Can those texts in English documents be protected to prevent from being translated?

- Cloud Volumes Service for AWS
- Cloud Volumes Service for Google Cloud
- Cloud Compliance
- Global File Cache
- Backup to Cloud
- Cloud Analyzer
- Cloud Tiering

**Comment by netapp-bcammett** [comment]
@akseldavis -- Can you help?

**Comment by akseldavis** [comment]
@yukakou will privately share feature roadmap.

**Comment by netapp-bcammett** [comment]
Do we need to keep this issue open?

**Comment by akseldavis** [comment]
I'm closing this issue. Yukako, please reach out to IE localization management with any concerns on how we will support in future.
