### ISSUE TITLE
Clarify when Saas-based UI is not enabled

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#420]
Page: [Frequently asked questions about Cloud Manager SaaS](https://docs.netapp.com/us-en/occm/faq_saas.html)

In the "Is the SaaS-based Cloud Manager compliant" section the following is stated:

"To comply with FedRAMP certification, the SaaS-based UI is not enabled for customers who require FedRAMP."

Can this be clarified to state that this is only for Cloud Central accounts using Azure or AWS Gov regions? I.E. -
"To comply with FedRAMP certification, the SaaS-based UI is not enabled for customers who deploy a Cloud Manager connector in Gov Cloud regions."

**Comment by netapp-bcammett** [comment]
As always, thank you for your feedback. I'm looking into this and will update when I get clarification.

**Comment by netapp-bcammett** [comment]
Hi again,

I updated the sentence just like you recommended. Thanks again for your feedback!
