### ISSUE TITLE
Clarify the requirement to have CM registered with NSS for updates

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/occm#431]
Page [1]: [Updating Cloud Volumes ONTAP software](https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html)

There's a page [2] about [registering systems](https://docs.netapp.com/us-en/occm/task_registering.html) with NetApp Support, but neither that page nor the one at the top mention that updates can work consistently across BYOL and PAYGO only if the systems are registered with NSS. BYOL CVO systems seem to be registered by default, but PAYGO are not. It is not clear from the explanation on page [2] whether "Support" includes things like "release notifications and software updates", and on page [1] there is no distinction between PAYGO and BYOL although the difference in registration (for PAYGO it is optional) may be significant.

I would suggest that this content be improved:

> Software updates must be completed by Cloud Manager
> Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

Proposed:

> Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.
> In order to receive notifications and get access to different CVO releases, PAYGO users need to have their system [registered with NSS](https://docs.netapp.com/us-en/occm/task_registering.html), while BYOL instances are registered by default

Feel free to change or maybe put a note about updates to page [2]. 
In any case I hope two points can be clarified:

- Do CVO PAYGO customers have to register with NSS to be able to receive update notifications and update CVO (using any approach, but especially S3/FTP/local image)?
- Does NSS-registered CVO PAYGO support alternative (S3, FTP, local image) updates the same way BYOL does?

**Comment by netapp-bcammett** [comment]
Thank you for the feedback, Sean. I understand what you're saying and will start working on the updates. 

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Sean,

I updated the upgrading page by adding a section that that says Cloud Volumes ONTAP must be registered with NetApp Support. Updated page: https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html

I also updated the registering page to note that it's required for upgrading PAYGO systems. Updated page: https://docs.netapp.com/us-en/occm/task_registering.html

Here's the commit that shows a diff of the changes (along with a few other unrelated changes):
https://github.com/NetAppDocs/occm/commit/5a08eca2ce68c05bc59a8fe491405c7f08a82e70

Please let me know if you think any additional changes are required.

Thanks,
Ben
