### ISSUE TITLE
Add if the resync and give back happens automatically in GCP

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#433]
Page: [High-availability pairs in Google Cloud Platform](https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html)

Hi, it would be useful to add to the explanation if the resync process and give back process happens automatically and transparent to application or if administrator needs to trigger manually these operations.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this suggestion, Gabriel. I'll check with my contacts to figure out what to document.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I added the following statement to the HA page:
"Storage takeover, resync, and giveback are all automatic by default. No user action is required."

Thanks again for your feedback.

Regards,
Ben
