### ISSUE TITLE
Add if storage resync and giveback in AWS happens automatically

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#434]
Page: [High-availability pairs in AWS](https://docs.netapp.com/us-en/occm/concept_ha.html)

If this process does happen automatically could we add that?
Or if administrator needs to do some manual operations, would be great to add that awareness in the text.

**Comment by netapp-bcammett** [comment]
Looking into this one too. Thanks!

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I added the following statement to the HA page:
"Storage takeover, resync, and giveback are all automatic by default. No user action is required."

Thanks again for your feedback.

Regards,
Ben
