### ISSUE TITLE
CVO for AWS single node (ONTAP 9.7 or earlier?) doesn't have core disk

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/occm#435]
Page: [Default configuration for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/reference_default_configs.html)

This page states that the CVO for AWS has a 540GB core disk.
> A 540 GB General Purpose SSD for the core disk

I've actually deployed CVO for AWS single instance and checked it, ONTAP 9.8 has the core disk, but 9.7 didn't have it.
Could you check the configuration and correct the page if wrong?

**Comment by netapp-bcammett** [comment]
Good catch! I updated the page as follows:

Starting with version 9.8, a 540 GB General Purpose SSD for a core disk when using a C5, M5, or R5 instance type

Thank you for submitting your feedback.

Regards,
Ben
