### ISSUE TITLE
Verify steps for assigning "Folder Viewer" to members of the service account

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/occm#443]
Page: [Set up Cloud Volumes Service for Google Cloud](https://docs.netapp.com/us-en/occm/task_setup_cvs_gcp.html)

The following feedback was emailed to us:

> Hello, 
> 
> only a little hint: 
> 
> •	please double-check the role „Folder Viewer“. This is not available in GCP. Adding CVS with owner permissions works. 

I followed the steps in the docs and I don’t see “Folder Viewer” either.

But I do see that the role exists in GCP: https://cloud.google.com/resource-manager/docs/access-control-folders#folder_viewer_role

And I see it in the GCP Console from the IAM Roles page:

![image](https://user-images.githubusercontent.com/18287750/101496896-53188600-3938-11eb-98bb-a362aede56c4.png)

**Comment by netapp-tonacki** [comment]
Ben, I see it still mentioned [in the Google page ](https://cloud.google.com/resource-manager/docs/access-control-folders#using_predefined_roles ), but you are right it is no longer on the NetApp doc page, so someone must have fixed this. I'll close it.  Thanks.
