### ISSUE TITLE
Incorrect reference

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#445]
Page: [Creating a Connector in GCP from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html)

This page states:

_
"Set up a service account that has the permissions that Cloud Manager needs to create and manage Cloud Volumes ONTAP systems in projects.

You’ll associate this service account with the Connector VM when you create it from Cloud Manager.

Create a role in GCP that includes the permissions defined in the Cloud Manager policy for GCP. Again, you’ll need to use the gcloud command line.

**The permissions contained in this YAML file are different than the permissions in step 2a.**"
_

I believe the reference to step 2a should be step 1.  The way it is right now it is referring to itself.

**Comment by netapp-bcammett** [comment]
Fixed. Thank you!!
