### ISSUE TITLE
Firewall Port 50000 for TLS?

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/occm#459]
Page: [Networking requirements for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/reference_networking_azure.html)

On-premises ONTAP is documented to have port 50000 open inbound for TLS communications used for the cluster peer connection.  Cloud Volumes ONTAP does not list this port in the networking requirement documentation.  Is this necessary for the cluster peer relationship between a CVO instance & on-prem ONTAP?

Thanks!
Ken

**Comment by netapp-bcammett** [comment]
Hi Ken,

Thank you for reaching out. Can you please share where you see that port 50000 is used for cluster peering? I do see it listed here for TLS: http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-49D0B88F-42CF-4766-A688-1C77A0AE8BD5.html

But I don't see port 50000 listed for ONTAP cluster peering prerequisites:
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-csp/GUID-729E6FCF-9640-47B8-8C20-EC0B89F8129B.html

Thanks,
Ben

**Comment by DrKeno** [comment]
Hi Ben!

The TLS requirement is based on the release notes for ONTAP 9.6 that indicate the cluster peer relationship is encrypted by default starting with that ONTAP release (page 18: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508).  The attached ONTAP Cluster Peering Encryption FAQ points out that cluster peering uses TLS 1.2 (FAQ found here: https://fieldportal.netapp.com/content/884270?assetComponentId=886079).

For that reason, since Cluster Peering uses TLS starting with ONTAP 9.6, it should be expected that the TLS 50000 port would need to be open in a firewall configuration where SnapMirror relationships are established between ONTAP clusters in the cloud and on-prem.  The question would be whether that would also be true between ONTAP Cloud instances.

Ken

**Comment by netapp-bcammett** [comment]
After some digging, we received confirmation: port 50000 is used by the Service Processor, so it doesn’t apply to Cloud Volumes ONTAP.
