### ISSUE TITLE
For adding SVMs: Steps need to be done on the Cloud Provider side as well 

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#466]
Page: [Managing storage VMs](https://docs.netapp.com/us-en/occm/task_managing_svms.html)

For  AWS you also need to create the secondary IP addresses.
I was working with a customer who had setup more SVMs via System Manager but until I directed them to add these the additional SVM is not reachable.

![image](https://user-images.githubusercontent.com/519212/105878653-42e36580-5fcf-11eb-969f-4eaa3a2e1dfa.png)

![image](https://user-images.githubusercontent.com/519212/105878751-5db5da00-5fcf-11eb-84d6-fc3f586895e6.png)

**Comment by netapp-bcammett** [comment]
Thank you for highlighting this, Richard. I'm planning to update the documentation with additional details as soon as I get information from engineering.

**Comment by netapp-bcammett** [comment]
Steps have been added here:

https://docs.netapp.com/us-en/occm/task_managing_svms.html#create-data-serving-storage-vms-for-cloud-volumes-ontap-in-aws

This page now describes how to allocate the IP address in AWS and how to create the storage VM and LIFs on Cloud Volumes ONTAP.
