### ISSUE TITLE
Consider to add Coldline and Archive storage classes in Google

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#467]
Page: [Learn about Backup to Cloud](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html)

At "Supported storage classes or access tiers" we say that "You can also use the lower cost Nearline storage class." but indeed, customer is able to set even Coldline and Archive.

Could you consider to modify or add a note that customer could modify from Google Console the object storage used to hold CBS data to use Coldline or Archive storage classes?

Regards.

**Comment by netapp-tonacki** [comment]
Hi Gabiel,  Thanks for the comment.   We just added Nearline to this doc page a couple weeks ago as a storage class we support. I don't know if we support these other classes at this time.  But I will check and get back to you.

Tom

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  We do support the Coldline and Archive storage classes, so I have added that information to the page.  Thanks again for bringing this up.

Tom
