### ISSUE TITLE
Issues in the Cloud Manager doc

### ISSUE THREAD

**Issue by banum-netapp** [NetAppDocs/occm#469]
Page: [Managing Azure credentials and subscriptions for Cloud Manager](https://docs.netapp.com/us-en/occm/task_adding_azure_accounts.html)

Hi, 
On this page, https://docs.netapp.com/us-en/occm/task_adding_azure_accounts.html#granting-azure-permissions-using-a-service-principal there are 3 items that need to be modified:
Under Creating an Azure Active Directory application
Step 4: Name: Enter a name for the application – should be test-service-principal (that is used later)
Redirect URI: the URI should be https://setup.cloudmanager.com?

In Assigning the application to a role
The az role definition crate command should create a role called Cloud Manager Operator role with that json file. (This role is assigned later to the test-service-principal.)

**Comment by banum-netapp** [comment]
I meant this for 
Redirect URI: the URI should be https://setup.cloudmanager.com

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this feedback. I'm going to check with our engineering and QA teams to confirm and then I'll update the docs accordingly.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi Banu,

Here's my reply to your feedback:

> Under Creating an Azure Active Directory application
> Step 4: Name: Enter a name for the application – should be test-service-principal (that is used later)

The name can be anything that a customer wants. The name that you've mentioned is an example in a screenshot that's used a few steps later. (I updated the page to note that the screenshot is an example.)

> Redirect URI: the URI should be https://setup.cloudmanager.com?

The URI is optional and can be anything. I've updated the page to note that you can skip it.

> In Assigning the application to a role
> The az role definition crate command should create a role called Cloud Manager Operator role with that json file. (This role is assigned later to the test-service-principal.)

Like I mentioned above, "test-service-principal" was just an example.

Thanks again for your feedback and please let me know if you have any additional comments.

Regards,
Ben
