### ISSUE TITLE
Backup time is based on which time zone?

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/occm#470]
Page: [Learn about Backup to Cloud](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html)

The following feedback was emailed to us:

> In this section:
> Backups are taken at midnight
> •	Daily backups start just after midnight each day.
> •	Weekly backups start just after midnight on Sunday mornings.
> •	Monthly backups start just after midnight on the first of each month.
> 
> Based on which time zone?
> Whatever the source ONTAP system is using?

**Comment by netapp-tonacki** [comment]
Thanks Ben,  I verified that Richard's assumption is correct that the backup start time is based on the time zone set on each source ONTAP system.  I will update the docs in the branch I plan to release in a few days, and I will respond to his email as well.

Thanks, Tom
