### ISSUE TITLE
Outbound internet access from your web browser is missing netapp.com

### ISSUE THREAD

**Issue by idontgit** [NetAppDocs/occm#48]
When accessing the OCCM GUI for the first time, authentication is done through netapp-cloud-account.auth0.com, but the web page includes content from services.cloud.netapp.com.
If this URL is denied, you cannot login to CloudCentral / OCCM ID.

**Comment by netapp-bcammett** [comment]
Thank you for your feedback. I added services.cloud.netapp.com to the list of web browser endpoints.

Please let me know if you have any further feedback.
