### ISSUE TITLE
We should state that the subnets cannot have overlapping CIDR ranges for the subnets used in the VPC0,1,2 and 3.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#486]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

**Comment by netapp-bcammett** [comment]
Thanks for pointing this out. I'll get this information added for the upcoming release.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
The following statement was added during a doc update yesterday:

`Note that the subnets in these VPCs must have distinct CIDR ranges. They can’t have overlapping CIDR ranges.`

Thanks,
Ben
