### ISSUE TITLE
Is it correct that description "on-prem ontap version is 9.6 or greater"?

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/occm#487]
Page: [Learn about Cloud Backup](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html)

> The ONTAP version must be 9.6 or greater in your Cloud Volumes ONTAP or on-premises systems.

Is the description above for CBS? Or for SnapMirror Cloud?
On-prem storage should be 9.7P5 or higher for CBS.

**Comment by netapp-tonacki** [comment]
Hi Kanitani,  Thanks for your comment.  When creating a backup 'from' an on-prem system we require 9.7P5, but this text description is specifically for performing a single file restore (SFR) operation.  I will double check with the engineering team to see if we need to list a version other than 9.6 for on-prem SFR.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Kanitani,  I verified with the engineering team that for the single file restore operation you only need 9.6 or greater.  9.7P5 is required only when creating the backup file from an on-prem system.

Thanks, Tom
