### ISSUE TITLE
CBS from on-prem requires Connector to be in the cloud text fix

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#488]
Page: [Learn about Cloud Backup](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html)

Hi, Cloud Backup Service requires that Cloud Manager Connector is deployed at the cloud (not on premises).
We should modify the Limitations text to avoid some confusion.
Currently: "When making backups from on-premises ONTAP systems, Cloud Manager must be deployed in the cloud. There is no support for on-premises Cloud Manager deployments."

Proposal: "When making backups from on-premises ONTAP systems, Connector must be deployed in the cloud. There is no support for on-premises Connector deployments."

Cheers,

**Comment by netapp-tonacki** [comment]
Hi Gabriel,  Thanks for your comment.  You are correct.  I have changed the wording to say 'Connector' instead of 'Cloud Manager'.

Thanks again for helping improve our docs.      Tom
