### ISSUE TITLE
Clarification regarding SaaS subscription

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#492]
Page: [Frequently asked questions about Cloud Manager SaaS](https://docs.netapp.com/us-en/occm/faq_saas.html)

We still experience confusion amongst customers (also support personnel) regarding the saas based subscription. For example:
• if it's needed at all if BYOL is active?
• what services rely on it outside of CVO?

There was an old communication sent out when saas became a thing. If we could put something similar in this section maybe?:
_**Starting June 2020, using add-on services such as integrated backup, privacy controls and performance 
monitoring, will require a one-time subscription to the SaaS Fulfilment Method on the Azure
Marketplace as well as for creating new Azure PAYGO Cloud Volumes ONTAP 9.7 instances.
Please note that previous subscription to Cloud Manager is still valid for Cloud Volumes ONTAP versions 
9.6 and below and this subscription is for new deployments of Cloud Volumes ONTAP versions 9.7 and 
above.**_

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this issue. This is great feedback. I'll work with folks on the Cloud Manager team to draft up the language and then I'll include it in the docs.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi again,

After discussing with product management, here's the text that is proposed for the documentation. Can you please take a look and let me know if this covers what you were looking for? Thanks!

> **When is a SaaS-based subscription required?**
>  
> A SaaS-based subscription is available from your cloud provider's marketplace to pay for the following as you go:
> 
> - Cloud Volumes ONTAP (starting with version 9.6 in AWS and GCP, and version 9.7 in Azure)
> - Cloud Backup
> - Cloud Compliance
> - Cloud Tiering
> 
> For Cloud Volumes ONTAP, Cloud Backup, and Cloud Tiering, you also have the option to purchase licenses directly from NetApp. In those cases, a SaaS-based subscription isn’t required.
>  
> A SaaS-based subscription is the only way to pay for Cloud Compliance.
>  
> When you get started with these services, Cloud Manager prompts you to subscribe if a subscription isn't in place. You'll only need to subscribe once--Cloud Manager uses the same subscription for each of these services.
>  
> <add links with more details about how to subscribe to each of these>

**Comment by laagabi** [comment]
Hi, That looks great to me!

**Comment by netapp-bcammett** [comment]
I added that content to the docs: https://docs.netapp.com/us-en/occm/faq_saas.html#when-is-a-saas-based-subscription-required

Thanks again!
