### ISSUE TITLE
MUST add a note about subnets 172.17.0.0/16 and 172.18.0.0/16

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/occm#497]
Page: [Creating a Connector in AWS from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html)

I've had two customers hit this issue in just a few months.  This is a total ship stopper for On-Prem discovery (and likely would impact other networking items).  The issue is that:

- By default the connector is deployed with two interfaces that are NOT obvious and are NOT visible unless you SSH into the instance.
- These interfaces have IP addresses 172.17.0.1 and 172.18.0.1 with /16 CIDRs
- IF the customer has a subnet configured with either of these ranges then connectivity to Cloud Manager will FAIL
- Specifically this has led to On-Prem cluster discovery failure
- IMPORTANT: This issue has led to WEEKS of troubleshooting including multiple vendors and multiple NetApp resources before finding the issue.
- The fix is to change the IP address to anything else and it's not fully understood what might be getting broken by doing this.

I've submitted JIRA:https://jira.ngage.netapp.com/browse/CDS-1778 which has been ignored.  A documentation update would at least give us something to give to customers so it's clear that these IP's are being deployed and 'could' impact discovery.

We need to, at the very least, make a clear NOTE somewhere in this deployment doc that warns of the possibility of IP overlap and maybe simply points to support for a 'fix' if we do not want to give instructions for changing the ip addresses on the EC2 instance.

Please let me know if you have questions or need additional info about this issue.  I'm happy to clarify to make sure the weight of this is understood.  Thanks!

**Comment by netapp-bcammett** [comment]
Thanks for reaching out. I do have one question: the Connector is deployed with these two interfaces (and the 172.x IP addresses) whether the Connector is deployed in AWS, Azure, or GCP, right? 

Just wanted to confirm since the issue was opened against the AWS page.

I do think we should point to support for a fix given what you've described.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Can you please take a look at the following proposed text for the docs:

> Possible conflict with IP addresses in the 172 range
> 
> Cloud Manager deploys the Connector with two interfaces that have the IP addresses 172.17.0.1/16 and 172.18.0.1/16.
> 
> If your VPC or VNet has a subnet configured with either of these ranges, then you will experience connectivity failures from Cloud Manager. For example, discovering on-prem ONTAP clusters will fail.
> 
> The workaround is to change the IP addresses of the Connector's interfaces. Contact NetApp Support for help.

I believe this should be a known issue in the release notes but that it should also be mentioned on the Networking page for the Connector: https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html

Thanks,
Ben

**Comment by randobrando46** [comment]
For accuracy I might say that it deploys interfaces with the IP addresses in the 172.17.0.0/16 and 172.18.0.0/16 ranges.

I might keep it a bit more vague with respect to where it could cause conflicts.  What I've specifically seen in both cases were that the on-prem networks had those subnets in use so I'm not sure what it would do if the vpc's / vnet's used those ranges.

Otherwise, awesome.  And thanks for the quick replies!

**Comment by netapp-bcammett** [comment]
Thanks for the feedback. I updated the statement about the CIDR ranges, changed "If your VPC or VNet..." to "If your network....", and made a few more slight tweaks. 

Here's the updated text:

```
Possible conflict with IP addresses in the 172 range

Cloud Manager deploys the Connector with two interfaces that have IP addresses in the 172.17.0.0/16 and 172.18.0.0/16 ranges.

If your network has a subnet configured with either of these ranges, then you might experience connectivity failures from Cloud Manager. For example, discovering on-prem ONTAP clusters in Cloud Manager might fail.

The workaround is to change the IP addresses of the Connector's interfaces. Contact NetApp Support for help.
```

**Comment by netapp-bcammett** [comment]
Closing the loop. 

This issue was documented in the known issues section of the Release Notes: 
https://docs.netapp.com/us-en/occm/reference_issues.html

It was also mentioned on the Networking requirements page for the Connector:
https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html

**Comment by randobrando46** [comment]
this is awesome - thanks Ben!
