### ISSUE TITLE
Outbound internet access from your web browser requires auth0.com without prefix

### ISSUE THREAD

**Issue by idontgit** [NetAppDocs/occm#50]
When accessing the OCCM GUI for the first time, authentication  seems to require access to auth0.com in general, not only netapp-cloud-account.auth0.com.
If this URL is denied, you cannot login to CloudCentral / OCCM ID.

**Comment by netapp-bcammett** [comment]
Thanks again for the feedback. I added auth0.com to the list of endpoints from your web browser.
