### ISSUE TITLE
Cloud Manager System ID changed, need update

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#500]
Page: [Finding your Cloud Manager system ID](https://docs.netapp.com/us-en/occm/task_finding_system_id.html)

New Cloud manager changed the place where System ID is displayed.
Would be great to have it updated.

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I just wanted to confirm that the following image matches what you're seeing:

![screenshot_system_id](https://user-images.githubusercontent.com/18287750/110798043-c12a5d00-8247-11eb-80e3-b39fe17a6520.gif)

As you can see, this is a 3.9.5 system (which is the upcoming version), so I wanted to make sure that it matches what you see in 3.9.4.

Thanks,
Ben

**Comment by gabrieltokyo** [comment]
Yes, It was like that in version 3.9.3 and also in current 3.9.4.

![image](https://user-images.githubusercontent.com/34706481/110895512-40e62380-833d-11eb-9372-092830169574.png)

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I updated the step and image in the docs.

As always, thank you for your feedback.

Regards,
Ben
