### ISSUE TITLE
Mention “Aggregate free space ratio for data tiering”  in aggr settings

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#501]
Page: [Managing data tiering from your clusters](https://docs.netapp.com/us-en/occm/task_managing_tiering.html)

Could we consider mentioning the “**Aggregate free space ratio for data tiering**” setting that is available in Cloud Manager?
Customers are often not aware of this setting, or the fact that it can be adjusted or disabled. It is also important because if the user has automatic capacity management enabled, Cloud Manager will purchase disks to expand the aggregate in case the free space ratio percentage is not met in the local tier.

Recently, our customer "All-for-one Steeb AG" had the following concern, not knowing that this setting existed:
_Right now the aggregate in our CVO has always 10% free space of the data tiered to object-storage. (e.g. 170 TB tiered to object-storage, 17TB free space minimum in CVO aggregate).
This is quite expensive and kinda useless on CVO instances (absolutely valid on local clusters to ensure some restore capability). But on CVO you can just add virtual disks if required so.
Our Aggregates are all just 20-40% filled. This costs us in total around 20.000 $ per month!!! additionally. (as we have over 170 CVO's running)_

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this issue. I just want to make sure that I understand.

The top of your GitHub comment links to a page that's about tiering data from on-prem ONTAP clusters using Cloud Tiering. But your comment is about tiering data from _Cloud Volumes ONTAP_ to object storage. And how you can change the free space ratio for Cloud Volumes ONTAP using this setting:

![free-space-for-tiering](https://user-images.githubusercontent.com/18287750/110813381-73692100-8256-11eb-85ad-083254ac5d59.gif)

Thanks,
Ben

**Comment by laagabi** [comment]
Hi Ben,

I believe this setting is applicable in both cases. If you add an onprem system to CM, this setting should also kick in, so that is why I initially went for https://docs.netapp.com/us-en/occm/task_managing_tiering.html 
I was also under the impression that this page is talking about tiering settings for both cases (onprem and cvo).

However, should that be not the case, then i think we can put it in here maybe:
https://docs.netapp.com/us-en/occm/task_tiering.html#tiering-data-from-read-write-volumes

**Comment by netapp-bcammett** [comment]
> I believe this setting is applicable in both cases. If you add an onprem system to CM, this setting should also kick in, so that is why I initially went for https://docs.netapp.com/us-en/occm/task_managing_tiering.html

I'll check, but I'm almost certain that this setting applies to Cloud Volumes ONTAP only.

> I was also under the impression that this page is talking about tiering settings for both cases (onprem and cvo).

This page applies to on-prem only since it's for Cloud Tiering. We'll look at that page and make sure that it's clear.

> However, should that be not the case, then i think we can put it in here maybe:
> https://docs.netapp.com/us-en/occm/task_tiering.html#tiering-data-from-read-write-volumes

Yes, that's the perfect spot for the info. I'll write up a draft and update this issue so that you can review it.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Here's a draft of the section for the docs. Can you please let me know if you think anything is missing or unclear?

> ### Changing the free space ratio for data tiering
> 
> The free space ratio for data tiering defines how much free space is required on Cloud Volumes ONTAP SSDs/HDDs when tiering data to object storage. The default setting is 10% free space, but you can tweak the setting based on your requirements.
> 
> For example, you might choose less than 10% free space to ensure that you are utilizing the purchased capacity. Cloud Manager can then purchase additional disks for you when additional capacity is required (up until you reach the disk limit for the aggregate).
> 
> The ratio is important for disaster recovery scenarios because as data is read from the object store, Cloud Volumes ONTAP moves the data to SSDs/HDDs to provide better performance. If there isn’t sufficient space, then Cloud Volumes ONTAP can’t move the data. Take this into consideration when changing the ratio so that you can meet your business requirements.
> 
> NOTE: This setting applies to Cloud Volumes ONTAP only.
> 
> Steps
> 
> 1. In the upper right of the Cloud Manager console, click the **Settings** icon, and select **Cloud Manager Settings**.
> 
> 2. Under **Aggregate Capacity Thresholds**, click **Aggregate free space ratio for data tiering**.
> 
> 3. Change the free space ratio based on your requirements and click **Save**.

**Comment by laagabi** [comment]
This looks great! :)

Just one more thing. Can we emphasize that automatic capacity management will take this into consideration? We had 1 or 2 cases in the past where CM suddenly purchased disks for no apparent reason. And when we looked at the logs we saw that it was due to the fact that the free space ratio was not honored on the local tier. Am not 100% sure if that is still a thing though.

**Comment by laagabi** [comment]
Ah, sorry never mind. I see it is already there...:

"Cloud Manager can then purchase additional disks for you when additional capacity is required (up until you reach the disk limit for the aggregate)."

Sorry again, long day. Please go ahead and commit the changes.

**Comment by netapp-bcammett** [comment]
The doc update is complete: https://docs.netapp.com/us-en/occm/task_tiering.html#changing-the-storage-class-for-tiered-data

Thanks again for your feedback!
