### ISSUE TITLE
Some sentences are lost on the Japanese page.

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/occm#509]
Page: [Data tiering overview](https://docs.netapp.com/us-en/occm/concept_data_tiering.html)

Hello there!

On Japanese page, I can't find following sentences which are published on English page.

1) "Data tiering in AWS" - "Storage classes"
---
The default storage class for tiered data in AWS is Standard. If you don’t plan to access the inactive data, you can reduce your storage costs by changing the storage class to one of the following: Intelligent Tiering, One-Zone Infrequent Access, or Standard-Infrequent Access. When you change the storage class, inactive data starts in the Standard storage class and transitions to the storage class that you selected, if the data is not accessed after 30 days.
---

2) "Data tiering in Azure" - "Storage classes"
---
The default storage access tier for tiered data in Azure is the hot tier. If you don’t plan to access the inactive data, you can reduce your storage costs by changing to the cool storage tier. When you change the storage tier, inactive data starts in the hot storage tier and transitions to the cool storage tier, if the data is not accessed after 30 days.
---

2) "Data tiering in GCP" - "Storage classes"
---
The default storage class for tiered data is the Standard Storage class. If the data is infrequently accessed, you can reduce your storage costs by changing to Nearline Storage or Coldline Storage. When you change the storage class, inactive data starts in the Standard Storage class and transitions to the storage class that you selected, if the data is not accessed after 30 days.
---

There may be other similar sentences which are not translated into Japanese. Could you confirm it all of this page?

All those untranslated sentences include Italic type(s) with "_" in raw text. This might be related this issue.

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this issue. That's a good catch.

@akseldavis -- what's the correct workflow to address this translation issue?

Thanks,
Ben

**Comment by akseldavis** [comment]
Thank you, @kmakoto-at-netapp, for bringing this issue to our attention. We are tracking this as an internal issue. Next week we will prioritize and investigate timeline of solutions.

**Comment by netapp-bcammett** [comment]
I'm going to go ahead and close this issue, since it's being tracked separately by our tools team and can't be resolved by making a direct change to the Cloud Manager docs.
