### ISSUE TITLE
This feature has been removed . Please update the doc.

### ISSUE THREAD

**Issue by sanjeshu** [NetAppDocs/occm#510]
Page: [Storage management](https://docs.netapp.com/us-en/occm/concept_storage_management.html)

Management of inodes with automatic capacity management
Cloud Manager monitors inode usage on a volume. When 85% of the inodes are used, Cloud Manager increases the size of the volume to increase the number of available inodes. The number of files a volume can contain is determined by how many inodes it has.

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for submitting this feedback. I have sent a note to our development team to confirm removal of this feature. I'll update the docs as soon as I receive confirmation.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I removed this section from the documentation. Thanks again for your feedback!
