### ISSUE TITLE
Add if a customer is able to reuse/transfer its BYOL licenses

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#517]
Page: [Licensing](https://docs.netapp.com/us-en/occm/concept_licensing.html)

It should be useful to write here if a customer is able to transfer its license, just a short guidance may be enough.
This will cover some doubts we see for big customer that want to buy 5years in one shot and they know they will need to change VPCs or change the cloud provider (cloud agnostic BYOLs).

**Comment by netapp-bcammett** [comment]
Thanks, Gabriel. I'm looking into this and will let you know when the doc update is ready.

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I updated the docs to include this info: https://docs.netapp.com/us-en/occm/concept_licensing.html#license-transfer-to-a-new-system

Please let me know if any other updates are needed.

Thanks again!

**Comment by gabrieltokyo** [comment]
Thank you, Ben.

Those additions are great. Nice improvements.
