### ISSUE TITLE
security style mixed - not best practise

### ISSUE THREAD

**Issue by bnille** [NetAppDocs/occm#519]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html)

Hi there

please do not give the advice to use rootvolume-security-style mixed for the additional SVMs.
In our experience it is the worst possible security style to use.
I would recommend to use unix.

Regards
Benny

**Comment by netapp-bcammett** [comment]
Hi again Benny,

Thank you for this comment, as well! I'm looking into this and hope to have it updated by tomorrow.

(Sorry for the late reply--I was out of the office for a few days.)

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Hi Benny,

The docs were updated earlier this week to show "unix" as the root volume security style.

Thanks again for your feedback.

Regards,
Ben
