### ISSUE TITLE
create data lif - failover-policy system-defined is not the best way in single node systems

### ISSUE THREAD

**Issue by bnille** [NetAppDocs/occm#520]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html)

Hi there,

create data lif cli command:
please change the value for failover-policy to disabled because in ONTAP there is only one port available on single node systems. 
Or add a hint for single node systems to change it to disabled - for HA "system defined" is ok.

If you use your cli command on Single Node systems you get the following Warning:
Warning: The configured failover-group has no valid failover targets for the LIF's failover-policy. To view the failover targets for a LIF, use the "network interface show -failover" command.

If you use failover-policy disabled in this case the warning will not appear.

Regards
Benny

**Comment by netapp-bcammett** [comment]
Hi Benny,

Thank you for providing this feedback. I added the following note under step 2a:

> If this is a single node system, then you should change the value of the -failover-policy parameter to _disabled_.

Here's the link to the updated section: https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html#create-a-storage-vm-and-lifs

Please let me know if you have any feedback about this change.

Thank you again for contacting us.

Regards,
Ben
