### ISSUE TITLE
Best practices to discover WEs by multiple connectors.

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#522]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/occm/concept_connectors.html)

Update this page to mention that:
• WorkingEnvironments can be discovered by 2 (or more) connectors at the same time for DR purposes (to switch over if one connector goes down and can`t be recovered...).
• Ensure to only use capacity management on the main connector while disabling on the others (can be enabled when you have to switch over to the other connector).

This was discussed with engineering via JIRA CDS-2584

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for providing this feedback. I added a new section to the "Learn about Connectors" page that describes these details:

https://docs.netapp.com/us-en/occm/concept_connectors.html#using-multiple-connectors-with-the-same-working-environment

Please let me know if you have any additional feedback.

Thanks again,
Ben
