### ISSUE TITLE
The label of the support configuration link remains labeled with the previous version

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/occm#532]
Page: [Planning your Cloud Volumes ONTAP configuration in AWS](https://docs.netapp.com/us-en/occm/task_planning_your_config.html)

Hi team,

The label of the support configuration link remains labeled with the previous version as follow:
  - "Supported configurations for Cloud Volumes ONTAP **9.8** in AWS"
  - "Supported configurations for Cloud Volumes ONTAP **9.8** in AWS"
  - "Storage limits for Cloud Volumes ONTAP **9.8** in AWS"

(All of those link to the documents of ONTAP 9.9.0)

**Comment by netapp-bcammett** [comment]
Great catch! That was a bad find and replace on my part. 

The page is now updated with the correct link text of 9.9.0.

Thank you for your help.

Regards,
Ben
