### ISSUE TITLE
Need documentation on usage of new service account functionality

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#534]
Page: [Managing users, workspaces, Connectors, and subscriptions](https://docs.netapp.com/us-en/occm/task_managing_cloud_central_accounts.html)

Creating/Managing Service Accounts has been documented here:
https://docs.netapp.com/us-en/occm/task_managing_cloud_central_accounts.html#creating-and-managing-service-accounts

But there is no documentation on actually using this new feature.  Items missing:

- How to get a bearer token with a service account.  This is covered when using a user ID at https://docs.netapp.com/us-en/occm/api.html but there is nothing documented about using a service account, which requires different fields than a user (i.e. 
![image](https://user-images.githubusercontent.com/33675510/115044176-40442e00-9ea3-11eb-9269-6c5810fa38fd.png) )

-API documentation for creating/maintaining Service Accounts.  This information is missing from both https://docs.netapp.com/us-en/occm/api.html and the embedded Cloud Manager Swagger interface.

**Comment by netapp-bcammett** [comment]
Hi Mike,

Thanks for reaching out. For the two issues that you noted:

1. Documenting how to get a bearer token with a service account is in the works. I'll let you know when that's done.
2. I've reached out to the development team to understand why the API reference doesn't include anything about service accounts.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi Mike,

I updated the docs based on your feedback. Here are the changes:

1. Obtaining the token is documented in these two places:
a. https://docs.netapp.com/us-en/occm/task_managing_cloud_central_accounts.html#obtaining-a-bearer-token-for-a-service-account
b. https://docs.netapp.com/us-en/occm/api.html#_managing_your_account_with_the_tenancy_api

2. You can find details about the service account API call in the Swagger interface for the Tenancy API:
https://cloudmanager.cloud.netapp.com/tenancy/api-docs/static/index.html

The Tenancy API is separate from the Cloud Manager API. I've noted that in the docs: https://docs.netapp.com/us-en/occm/task_managing_cloud_central_accounts.html#managing-your-account-with-the-tenancy-api

Note that we're in the middle of revamping the API documentation. As part of this update, we'll make the relationship between all of the APIs that fit into the Cloud Manager platform more clear.

Please let me know if you have any additional feedback.

Thanks,
Ben
