### ISSUE TITLE
Add Volume size modifications

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#536]
Page: [Managing existing storage](https://docs.netapp.com/us-en/occm/task_managing_storage.html)

Could we add a "Resizing a volume" information part?
(Or is it already in another section, wich?)

It could be something like:
By default, Connector automatically grows your volumes a defined times the original size.
You can check autogrow settings at ....

If you need to resize your volume you can do it through ONTAP System Manager, CLI but take into considerations following points:
  System maximums (licensing, etc)
  etc

Cheers,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for reaching out and submitting this request. I've add this one to my to-do list and will reach out with any questions. I'll let you know when this is ready.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
I added a section for resizing a volume based on your recommendation.
https://docs.netapp.com/us-en/occm/task_managing_storage.html#resizing-a-volume

Sorry for the delay and thanks again for submitting this feedback.

Regards,
Ben
