### ISSUE TITLE
I don't know what to enter in the "Storage Server" input field.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/occm#554]
Page: [Backing up on-premises ONTAP data to the private cloud](https://docs.netapp.com/us-en/occm/task_backup_onprem_private_cloud.html)

> 3. Enter the StorageGRID details
> Select StorageGRID as the provider, and then enter the StorageGRID details. You also need to specify the IPspace in the ONTAP cluster where the volumes reside.

Is there a commentary somewhere?
I don't know what to enter in the "Storage Server" input field due to lack of explanation.

Make sure that someone other than the person who wrote the manual can set it according to the procedure before publishing the manual.

**Comment by kanitani** [comment]
I found the description at the bottom of the page.

>Select StorageGRID as the provider, click Next, and then enter the provider details:
>The FQDN of the StorageGRID server, Access Key, and the Secret Key used to access the bucket to store backups.
>The IPspace in the ONTAP cluster where the volumes you want to back up reside.

It's better to improve the UI, not modify the documentation.

**Comment by netapp-tonacki** [comment]
Hi Kanitani,  I'm glad you were able to find what you were looking for in the docs. I'll relay your suggestion to the development team about possibly adding a hint in the UI about the information required in this field.
