### ISSUE TITLE
English version and Japanese version are differents

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#555]
Page: [システム間でのデータのレプリケーション](https://docs.netapp.com/ja-jp/occm/task_replicating_data.html)

Hi, not sure if we are working on an updated Japanese version of this page but just in case, it looks like new updates to this page in the English version have not propagated to the Japanese version.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/34706481/117602126-e6c1dd00-b18a-11eb-9c33-a9bbd400dc29.png">

**Comment by netapp-bcammett** [comment]
cc @akseldavis

**Comment by akseldavis** [comment]
@gabrieltokyo our Japanese content was previously unable to deploy due to the size of the site PDF. The Japanese site PDF will temporarily point to the English version while our team decides on a long-term strategy. We would be grateful for your review and confirmation that the Japanese content now reflects the English.

Thank you for helping us improve the quality of our documentation.

**Comment by gabrieltokyo** [comment]
Hi Aksel, now is better. Looks like the English version.

Nevertheless, I see many bugs in the Japanese side:
(Not sure is prefer a separated ticket for each one but compiling them roughly)

1) Some translations are deficient
   https://docs.netapp.com/ja-jp/occm/concept_replication.html
   Here "Features" (機能), became "Features of" (の機能). It maybe due to punctuation signs lack or context problem.
2) Bold letters styles confused
   https://docs.netapp.com/ja-jp/occm/task_replicating_data.html
   At the steps of "Setting up data replication between systems" (システム間のデータレプリケーションの設定), (I guess) the automated translation added spaces between the asterisk characters considering them part of the translation and for that something like **Source and Destination Peering Setup** became * Source and Destination Peering Setup * without getting translated and without bold style; or * ソースボリュームの選択 * (translated but with wrong style).
3) Some paragraph titles are lost
   https://docs.netapp.com/ja-jp/occm/task_replicating_data.html
   At the bottom of the page, the last title "Result" has disappeared in the Japanese version.
4) Similar problems at "Manage Schedules and relationships"
   https://docs.netapp.com/ja-jp/occm/task_managing_replication.html
   At the steps the bold styled Replication word became [*Replication] (wrong bold style and not translated)
   The end of the steps, the last title "Result" has disappeared in the Japanese version.
5) Similar problems at "Learn about replication policies"
   https://docs.netapp.com/ja-jp/occm/concept_replication_policies.html
   At the types of replication policies the italic style was badly interpreted by the translation causing all policy names like A _Mirror_ policy A_Mirror_policy (wrong style and affecting translation). Here you have to take care on the translation as you may want to avoid translation of Mirror in this context (policy name that should not be translated).

So far these are the problems I found (not entering into Japanese accuracy).
Cheers,

**Comment by akseldavis** [comment]
Thank you, @gabrieltokyo. This is very helpful feedback. I have shared this specific feedback with our L10n team for future improvements. I'm going to close this issue since the original problem has been addressed.
