### ISSUE TITLE
Clarification on very large datasets

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#560]
Page: [Cloud Sync technical FAQ](https://docs.netapp.com/us-en/occm/faq_sync.html)

On this page the following in stated:
"What if I have a very large dataset?
If a single directory contains 600,000 files or more, contact us so we can help you configure the data broker to handle the payload. We might need to add additional memory to the data broker machine."

We are being asked for clarification on 600,000 files or more in a single directory.  Does this mean 600,000 files in a single directory, exclusive of subdirectories?  Or any directory that has over 600,000 files including the contents of all subdirectories?

**Comment by netapp-bcammett** [comment]
Hi Mike,

I've reached out to the Cloud Sync team for clarification. I'll let you know what I hear.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Mike,

Here's the clarification that I received:

> That is for 600K files flat in a single directory no matter of how many subdirectories are there…
> Basically, a directory is being scanned by a single scanner process, meaning – one directory cannot be scanned by 2 or more processes.
> 
> So for a single process to list and scan a directory with more than 600K files in it- it requires extra memory for that process, so in that case we ask the machine to have more memory and then set the processes to utilize more memory.
> By default there are 2GB RAM for each scanner (4 processes by default), so for 1 million files flat – we will allocate 4GB for each scanner process and so on for 2M files…

Let me know if this is clear. I can summarize these details and update the FAQ.

Thanks,
Ben

**Comment by mimitche** [comment]
Ben-

Thanks for getting the additional info.  I'm still not 100% clear though.  Am I understanding correctly that I can have more than 600k files in a top level directory as long as no individual directory has more than 600k files?  I.E this is ok for the default memory configuration:

-Topdir1
     -500k files at topdir1 level
     -subdir1
             -500k files under subdir1
     -subdir2
            -500k files under subdir2

1.5 million files total under topdir1 and all subdirectories

**Comment by avi-dahan** [comment]
Hi Mike, that is correct, per your example - in such dataset structure you may use the default settings.
There is no limit to the total number of files in the mount point.
The extra memory is required for 'huge directories, regardless of their level - top directory or subdirectories.

**Comment by mimitche** [comment]
Thanks- that makes sense now; appreciate the clarification.

**Comment by netapp-bcammett** [comment]
Mike and Avi,

Does the following change to the FAQ help:

> **What if I have a very large dataset?**
> 
> If a single directory contains 600,000 files or more, contact us so that we can help you configure the data broker to handle the payload. We might need to add additional memory to the data broker machine.
> 
> Note that there's no limit to the total number of files in the mount point. The extra memory is required for large directories with 600,000 files or more, regardless of their level in the hierarchy (top directory or subdirectory).

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I published the change. Thanks again for the feedback!
