### ISSUE TITLE
Update CVO HA Diagram

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/occm#564]
Page: [High-availability pairs in Google Cloud Platform](https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html)

The diagram is missing the orange dotted HA connection from Node2 NAS traffic box to Node1 NAS traffic LIFs box.  I've attached a modified drawing to illustrate what I mean.
![GCP-ha-diagram](https://user-images.githubusercontent.com/46236887/118896629-aa9f2280-b8d6-11eb-97e0-42bfd6c84bbf.png)

**Comment by netapp-bcammett** [comment]
Hi Scott,

Good catch. Thank you for submitting this issue. I updated the graphic to add the dotted arrow.

Thanks again,
Ben

**Comment by scottkntap** [comment]
Great, thank you sir!


Best Regards,

Scott Kovacs
Customer Success Engineer
Cloud Customer Success

NetApp
919.476.4560 Direct Phone
919.946.3044 Mobile Phone
***@***.******@***.***>

[A close up of a sign  Description automatically generated]<https://cloud.netapp.com/>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>



From: Ben Cammett ***@***.***>
Reply-To: NetAppDocs/occm ***@***.***>
Date: Thursday, May 20, 2021 at 12:41 PM
To: NetAppDocs/occm ***@***.***>
Cc: "Kovacs, Scott" ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/occm] Update CVO HA Diagram (#564)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Scott,

Good catch. Thank you for submitting this issue. I updated the graphic to add the dotted arrow.

Thanks again,
Ben
