### ISSUE TITLE
Additional Information AWS C2S environment

### ISSUE THREAD

**Issue by DP0077** [NetAppDocs/occm#569]
Page: [Get started with Cloud Volumes ONTAP in the AWS C2S environment](https://docs.netapp.com/us-en/occm/task_getting_started_aws_c2s.html)

Please add a section stating that "Networking requirements for the Connector" are still required specifically "Endpoints to install the Connector on a Linux host" and "Endpoints accessed from your web browser when using the local UI". I had a client try to complete the install with NO internet connectivity.

**Comment by mimitche** [comment]
@DP0077 - Please confirm the page you linked in this report. That page is specifically for the AWS C2S environment which has NO internet connectivity.  C2S is a government related region and is not available to any commercial customers or even most government customers.

**Comment by DP0077** [comment]
@mimitche - I can confirm that is the guide that the customer was trying to follow as they did not have internet access in there environment. Nothing on that page stipulated that it was not available.

**Comment by mimitche** [comment]
@DP0077 If the client is a C2S user please contact me internally (michael9) for further information.  If the client is not a C2S user the documentation on this page does not apply.

**Comment by netapp-bcammett** [comment]
We'll come up with wording for the C2S page that may help avoid future confusion.

**Comment by netapp-bcammett** [comment]
The C2S page was updated to clarify that these instructions apply only to users in the C2S region.

https://docs.netapp.com/us-en/occm/task_getting_started_aws_c2s.html
