### ISSUE TITLE
Clarification on BYOL license expriy alerts/warnings and notifications

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/occm#573]
Page: [Licensing overview for BYOL](https://docs.netapp.com/us-en/occm/concept_licensing.html)

Hi Team,

We've had a NetApp customer share some feedback as their BYOL license expired resulting in their CVO shutting down. They asked why they were not notified about this. 

Reviewing this licensing section of the documentation it indicates in the first paragraph that "notifying you before they expire", but reading further down the page, you realise that notification is only a warning alert within Cloud Manager itself, not an email notification of any kind. 

This article then has a warning box stating that if you want email notifications you have to configure them on ONTAP on the CVO and enable email alerts for the EMS events, but doesn't clarify which events will refer to the license expiry, when they will show, how often etc. 

I think this particular article could be expanded slightly to make it clearer on what and where notifications occurs, and the difference between a warning / alert and a notification. Notification terminology implies email notification to alot of customers.

Hope this helps!

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this feedback. Your explanation of the issue makes perfect sense. I'll look into this and get back to you with any questions and would love to share the proposed update with you when it's ready.

Thanks again for your help.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Hi again,

I updated the "Licensing overview" page to update terminology and to describe how to receive notifications through the Cloud Volumes ONTAP report. Please take a look and let me know if you think any additional changes are needed.

https://docs.netapp.com/us-en/occm/concept_licensing.html

Thanks,
Ben

**Comment by roscocheeta** [comment]
Thanks Ben.

The changes are a lot clearer now. 

I wonder if its worth reviewing the BYOL Backup License section too over at - https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html#bring-your-own-license 

As I am guessing there is some similarities in the terminology used and how warnings are displayed for that license type as well.

**Comment by netapp-bcammett** [comment]
@netapp-tonacki, we had a bit of confusion around the term "notification" when it came to license expiration for Cloud Volumes ONTAP (see the previous comments in this GitHub issue). The same confusion might apply to Backup BYOL licenses.

We should probably modify the following text to clarify what we mean by notifications:

> When using a Cloud Backup BYOL license, Cloud Manager notifies you when backups are nearing the capacity limit or nearing the license expiration date. You receive these notifications:
> 
> * When backups have reached 80% of licensed capacity, and again when you have reached the limit
> 
> * 30 days before a license is due to expire, and again when the license expires
> 
> Use the chat icon in the lower right of the Cloud Manager interface to renew your license when you receive these notifications.

To match what we say for Cloud Volumes ONTAP BYOL, we could change it like so:

> When using a Cloud Backup BYOL license, Cloud Manager displays a warning in the user interface when backups are nearing the capacity limit or nearing the license expiration date. You receive these warnings:
> 
> * When backups have reached 80% of licensed capacity, and again when you have reached the limit
> 
> * 30 days before a license is due to expire, and again when the license expires
> 
> Use the chat icon in the lower right of the Cloud Manager interface to renew your license when you see these warnings.

What do you think?

**Comment by netapp-tonacki** [comment]
That looks great.  Thanks Ben.  I'll make this change shortly.

**Comment by netapp-tonacki** [comment]
Hi, I have made the changes to the [Backup section](https://docs.netapp.com/us-en/occm/concept_backup_to_cloud.html#bring-your-own-license) that Ben suggested.  Think we can close this out now.  Thanks for the suggestions to clarify these topics.
