### ISSUE TITLE
Edit for WORM page "Limitations" section

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/occm#581]
Page: [WORM storage](https://docs.netapp.com/us-en/occm/concept_worm.html)

Hello again,
Working with the SnapLock P-team, we're requesting another change to this page's "Limitations" section. Currently, the first bullet of this section is:
"
- WORM storage in Cloud Volumes ONTAP operates under a "trusted storage administrator" model. While WORM files are protected from alteration or modification, volumes can be deleted by a cluster administrator even if those volumes contain unexpired WORM data.
For example, if you delete or move a disk directly from your cloud provider, then a volume can be deleted before its expiry date.
"

We'd like to break this out into two distinct bullets for additional clarity:
"
- WORM storage in Cloud Volumes ONTAP operates under a "trusted storage administrator" model. While WORM files are protected from alteration or modification, volumes can be deleted by a cluster administrator even if those volumes contain unexpired WORM data.

- In addition to the trusted storage administrator model, WORM storage in Cloud Volumes ONTAP also implicitly operates under a “trusted cloud administrator” model. A cloud administrator may delete WORM data before its expiry date by removing or editing cloud storage directly from the cloud provider.
"

Please let me know if you have any questions on this request. Thanks!

**Comment by netapp-bcammett** [comment]
Hi again,

Thank you for taking the time to submit this feedback. The change makes sense and will be simple. I'll let you know when it's done.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Made the requested changes:
https://docs.netapp.com/us-en/occm/concept_worm.html#limitations

Thanks again for your feedback!
