### ISSUE TITLE
Adding more steps in this page

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#582]
Page: [Setting up an AWS transit gateway for HA pairs in multiple AZs](https://docs.netapp.com/us-en/occm/task_setting_up_transit_gateway.html)

Hello team.

I'me requesting adding two steps to clarify the process to configure an AWS Transit Gateway and mount the volume.

 - For the TGW part, before creating static and propagating the routes I will add the Associations step. So in Transit Gateway Route Table we need to go to Associations and attach our VPC's (attachments) created before. This is a little bit tricky as is not in AWS TGW Creation process but necessary to work.
 - For the last step in this page in mounting part I would add the step to configure the correct export-policy in case we're mounting a NFS volume as some of our customers are not coming from ONTAP world, they have to set the export-policy to match the subletting in the client VPC.

Thanks so much.

**Comment by netapp-bcammett** [comment]
Hi Javier,

Thank you for taking the time to submit this feedback. The suggested changes make sense at a high level. Once I start to work on the updates, I'll get back to you if I have any questions.

Thanks again,
Ben

**Comment by jsuarezs** [comment]
Sure Ben, just let me know any questions so far contacting to me by Teams or by email jsuarezs@netapp.com if I can help somehow.

Regards.

**Comment by netapp-bcammett** [comment]
Steps 2 and 6 are new based on the feedback:
https://docs.netapp.com/us-en/occm/task_setting_up_transit_gateway.html

Confirmed with Javier that the updated docs look good.
