### ISSUE TITLE
Add more information regarding the IPs needed

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#587]
Page: [Networking requirements for Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/reference_networking_aws.html)

Hello team.

I'm working already with customers that found the IPs information very light. I mean, it would be really nice to have documented deeper the IP scope because for the largest of our customers I can see that they're really worried about the 15(16) IPs consuming model is quite a lot looking for the future to deploy several CVOs so they need to know exactly for what purpose every single IP is used for very kind of deployments.

This will be very useful also for us to have things clear in networking scope, a really interesting point to do the subnetting.

Thanks so much.

**Comment by netapp-bcammett** [comment]
Thank you, Javier. I've reached out to the engineering lead and he will get back to me with the details.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Javi,

I updated the AWS networking requirements page by adding details about the purpose of each LIF, as well as a graphic showing where the communication takes place. 

https://docs.netapp.com/us-en/occm/reference_networking_aws.html#private-ip-addresses

Please let me know if you think any additional changes are needed.

Thanks again for the feedback.

Regards,
Ben

**Comment by jsuarezs** [comment]
Hello Ben.

I think is really useful right now since several customers were asking for that.

I really appreciate your job.

Gracias, un saludo.
