### ISSUE TITLE
Do we have a 10,000 foot view to include here?

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#593]
Page: [Using Cloud Volumes ONTAP as persistent storage for Kubernetes](https://docs.netapp.com/us-en/occm/task_connecting_kubernetes.html)

Hello team. I got request for at least two customers asking for an architecture diagram in AWS using EKS and CVO. I think this is something we should have here to let them know in the documentation not only the requisites.

Indeed, it would be good to have this for every hyperscaler.

Thank you so much.

**Comment by netapp-bcammett** [comment]
Hi Javier,

There is an example diagram here for EKS:
https://docs.netapp.com/us-en/occm/task_connecting_kubernetes.html#example-setup

Are you looking for something more detailed? If yes, what are the other details that you'd like to see?

As always, thanks for the feedback.

Regards,
Ben

**Comment by jsuarezs** [comment]
Hello Ben.

Usually EKS deployment in AWS is made in a different VPC stack which is typed in our documentation as follows. 

Both the Connector and Cloud Volumes ONTAP need a connection to the Kubernetes API endpoint:
For managed clusters, set up a route between a cluster’s VPC and the VPC where the Connector and Cloud Volumes ONTAP reside.


It would be great to have an AWS diagram showing both VPCs and the networking in the middle and more documented details in this process like which Security Groups and routes are needed from both source and destination to establish the peering between EKS and CVO. Normally AWS customers looking for NetApp solutions like to see the typical AWS diagrams showing all the details to have in place a CVO connected to AWS EKS.

Thanks so much.

Gracias, un saludo.

**Comment by netapp-bcammett** [comment]
Got it. I'll check with the experts in this space and see what I can do.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Javier,

Here's what I heard from the team:

> - VPC peering is the easy way but any other method will work: https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/amazon-vpc-to-amazon-vpc-connectivity-options.html
> 
> - Security group: https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html 
> 
> No other networking is needed AFAIK

So I can update the existing graphic by showing VPC peering and we can include this link about security groups for EKS clusters:
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

Thanks,
Ben

**Comment by jsuarezs** [comment]
Hello Ben.

This sounds really better than before in the web page, thanks so much for taking into consideration. Let me know once done.

Regards,

Javi.

**Comment by jsuarezs** [comment]
Hello Ben.

I was working by myself and it would be good to have an AWS aporoach in the diagrams for this cloud provider. I’m attaching something that could work and this is something that can be used also as reference for the VPC pering case (without using AWS TGW).

[Interfaz de usuario gráfica, Diagrama, Aplicación  Descripción generada automáticamente]
I hope it helps somehow.

Regards,

Javi.

--
Javier Suárez Sanz
Cloud Solutions Engineer
+34 673 546 938

NetApp
***@***.******@***.***>

[A picture containing bird  Description automatically generated]<https://www.netapp.com/us/index.aspx>



De: Javier Suárez ***@***.***>
Fecha: domingo, 20 de junio de 2021, 21:27
Para: NetAppDocs/occm ***@***.***>
CC: NetAppDocs/occm ***@***.***>, Author ***@***.***>, Suarez, Javier ***@***.***>
Asunto: Re: [NetAppDocs/occm] Do we have a 10,000 foot view to include here? (#593)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello Ben.

This sounds really better than before in the web page, thanks so much for taking into consideration. Let me know once done.

Regards,

Javi.


El 16 jun 2021, a las 14:40, Ben Cammett ***@***.***> escribió:
﻿

Javier,

Here's what I heard from the team:

  *   VPC peering is the easy way but any other method will work: https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/amazon-vpc-to-amazon-vpc-connectivity-options.html
  *   Security group: https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

No other networking is needed AFAIK

So I can update the existing graphic by showing VPC peering and we can include this link about security groups for EKS clusters:
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Javi,

I updated the example graphic to show a VPC peering connection. Please take a look:
https://docs.netapp.com/us-en/occm/task_connecting_kubernetes.html#example-setup

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
No additional changes were requested, so I'm going to close this issue.

**Comment by jsuarezs** [comment]
Thanks for additional the picture Ben. I really appreciate it one more time.

Regards,

Javi.

Gracias, un saludo.
