### ISSUE TITLE
Does other products (CBS, Tiering, etc) license expiration notifications arrive with same setting?

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#594]
Page: [Licensing overview for BYOL](https://docs.netapp.com/us-en/occm/concept_licensing.html)

Current text says:
"Cloud Manager includes a license expiration warning in the Cloud Volumes ONTAP report that’s emailed to you..."

Is that exclusively for CVO or will also other products license expiration warnings will arrive (CBS, Tiering, etc)?
If other products expirations are also covered, could we modify the text to include them?

Thank you,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

The report is exclusively for CVO.

Regards,
Ben
