### ISSUE TITLE
Title change proposal (from Cloud Manager to Connector)

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#595]
Page: [Finding your Cloud Manager system ID](https://docs.netapp.com/us-en/occm/task_finding_system_id.html)

I believe we should review this title:
"Finding your Cloud Manager system ID"

Propose to change it to:
"Finding your Connector system ID"

**Comment by netapp-bcammett** [comment]
Thank you for submitting this request, Gabriel. The page has been updated:
https://docs.netapp.com/us-en/occm/task_finding_system_id.html

Thanks again,
Ben
