### ISSUE TITLE
Step 10 under IAM role does not provide the correct link to the policy requirements for CVO

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/occm#598]
Page: [Launching Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/task_deploying_otc_aws.html)

Looking at step 10 on this page-
If you click on the link, it only takes you to the Support page instead of the policy requirements page.

IAM Role: It’s best to keep the default option to let Cloud Manager create the role for you.
If you prefer to use your own policy, it must meet policy requirements for Cloud Volumes ONTAP nodes.

**Comment by netapp-bcammett** [comment]
Thank you for pointing this out. I'll get this fixed and let you know when it's done.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
The link has been fixed. Thanks again!
