### ISSUE TITLE
Wrong reference in Tenant ID documentation

### ISSUE THREAD

**Issue by pascaldewild** [NetAppDocs/occm#605]
Page: [Manage licenses](https://docs.netapp.com/us-en/occm/task_managing_licenses.html)

In the paragraph of "Obtaining your Cloud Backup License", it says you have to enter your Cloud Connector System ID in the "Tenant ID" field. This is incorrect, this should be the Account ID, which is on the main overview page in the Cloud Manager. 

Or at least, it doesn't accept the System ID (as referenced), it requires input starting with 'account-'.

Can you please update this, as my customer ran into this (and was luckily smart enought to figure out the account ID :) )

Thanks, 
Pascal de Wild - SE - NetApp Netherlands.

**Comment by netapp-tonacki** [comment]
Hi Pascal,  You are correct.  I will change that today to "Cloud Manager Account ID".  Thanks for your correction.

Tom

**Comment by netapp-tonacki** [comment]
Hi,  This has been corrected.  Thanks again for the feedback from you and from our customer.
