### ISSUE TITLE
Support for CentOS Stream

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#615]
Page: [Installing the data broker on a Linux host](https://docs.netapp.com/us-en/occm/task_sync_installing_linux.html)

Hello Team,

Could we mention here that CentOS Stream is not supported? Encountered this with a customer in case 2008841729 where they had a failed on-prem broker running centos stream 8. 

Thanks in advance,
Gabor.

**Comment by netapp-bcammett** [comment]
Hi Gabor,

Thank you for submitting your feedback. I updated the page to state the following:

"CentOS Stream is not supported." 

Thanks again,
Ben
