### ISSUE TITLE
Misleading wording on permissions for cloud restore

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#617]
Page: [Backing up Cloud Volumes ONTAP data to Amazon S3](https://docs.netapp.com/us-en/occm/task_backup_to_s3.html)

This statement is incorrect:

        AWS Restore permissions required
        
            The following permissions are needed **in the policy for the Cloud Restore instance**:

These permissions are for the cloud manager to be able to start, stop and terminate the cloud restore instance.

**Comment by netapp-tonacki** [comment]
Hi Richard.  Thanks for the correction.  I worked closely with the team when adding the Restore instance wording, so let me double-check to see why I added what's in the docs.  I've sent them a message and will get back to you.

Thanks, Tom

**Comment by nichollri** [comment]
Hey.  I am checking in on this.  I still think the wording is incredibly misleading
It says: "The following permissions are needed **in the policy for the Cloud Restore instanc**e:"

It's a case of bad reference of determining what "the policy" is.  In this case it is referring to the Cloud Manager policy.
So if the statement read more like what is above in the AWS Backup permissions required it would be better.
Here is what I suggest:
_The IAM role that provides Cloud Manager with permissions must include EC2  permissions to be able to start, stop and terminate the cloud restore instance._

Cloud Manager actually has a role created and attached to it when it is deployed and it is these permissions.
And this is an actual hole in the documentation.  I have a customer that does not allow Cloud Manager to create roles.  In this case the role has to be applied to the cloud restore instance AFTER it is first created.

Here is the role/permissions that are added to the cloud restore instance by Cloud Manager:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow"
        }
    ]
}

I am going to open up an RFE against Cloud Backup Service so that a pre-existing role can be selected during the SFR process.

**Comment by netapp-tonacki** [comment]
Hey Richard,  Sorry for the delay.  I had added some changes for the August sprint, but those new Cloud Backup features just went live today. So I revised the content again based on your suggested wording.  I am pushing the new content live right now, so please take a look and let me know what you think.

Tom

**Comment by nichollri** [comment]
New wording is perfect!  Thanks.

**Comment by netapp-tonacki** [comment]
Thanks Richard.

Tom
