### ISSUE TITLE
Clarification needed on single file restore flows/protocols

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#618]
Page: [Backing up Cloud Volumes ONTAP data to Amazon S3](https://docs.netapp.com/us-en/occm/task_backup_to_s3.html)

There is a diagram on this page outlining flows and protocols used for backup and restore.  For single file restore, the Cloud Restore Instance is listed, but does not have protocols listed.  A customer is requesting more information on what flows/protocols happen between the restore instance and other components for security approval.  Flows in question identified with red arrows in attached image.

![image](https://user-images.githubusercontent.com/33675510/126803626-d817ecc0-8ef3-496c-84d4-d168d9c209c5.png)

**Comment by netapp-tonacki** [comment]
Hi mimitche, Thanks for your comment.  I'll check with the team and get back to you.  I'll update that diagram, and the others for Azure, etc. when I hear.

Thanks, Tom

**Comment by mimitche** [comment]
Hi Tom-  Just checking in; any news back from the CBS team?  I have a customer who is holding off on this until we can document ports/protocols needed for flows to/from the Cloud Restore instance.

**Comment by netapp-tonacki** [comment]
Hi mimitche, I just heard back late yesterday that it is also HTTPS (port 443).   I will be updating the diagrams in the next few days.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi mimitche, The diagrams showing the HTTPS connections are updated in the live site now.

Thanks again for your comment, Tom
