### ISSUE TITLE
Need more detailed flow info for VPCs 1-3

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#619]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

On this page the following is stated:
_"Firewall rules for VPC-1, VPC-2, and VPC-3
In GCP, an HA configuration is deployed across four VPCs. The firewall rules needed for the HA configuration in VPC-0 are listed above for Cloud Volumes ONTAP.

Meanwhile, the predefined firewall policy that Cloud Manager creates for instances in VPC-1, VPC-2, and VPC-3 enables ingress communication over all protocols and ports. These rules enable communication between the HA nodes and the HA mediator."_

I have a customer that needs more information on the specific ports/protocols (flows) used on VPC1, VPC2, and VPC3 in order for security approval.  Can this information be added to the documentation?

**Comment by netapp-bcammett** [comment]
Hi Mike,

Thank you for submitting this feedback. I've copied you on an email with the subject matter expert to identify the required info. After I get that, we'll update the docs.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
I added details about port 3260 here:
https://docs.netapp.com/us-en/occm/reference_networking_gcp.html#firewall-rules-for-vpc-1-vpc-2-and-vpc-3

Other ports used for internal communication between HA nodes is being tracked through this issue:
https://github.com/NetAppDocs/occm/issues/633

Thanks,
Ben
