### ISSUE TITLE
CentOS 7.9 is supported

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#632]
Page: [Connector host requirements](https://docs.netapp.com/us-en/occm/reference_cloud_mgr_reqs.html)
If you create a connector from Cloud Central for GCP, the version that is currently being installed is CentOS 7.9.
I also did the manual install using CentOS 7.9 and it worked.  I believe CentOS 7.9 should be added to this list.

**Comment by netapp-tonacki** [comment]
Hi Richard,  Thanks for checking and for letting us know.  Sounds like it should be added.  I'll double-check that there is no reason not to make this update.  I'll also check about adding CentOS 7.8 since we don't list that as supported; but do list Red Hat 7.8.

Thanks, Tom

**Comment by netapp-bcammett** [comment]
We updated the docs by adding CentOS 7.8 and 7.9.

Thank you for finding this, Richard.

Regards,
Ben
