### ISSUE TITLE
reword this document warning to inlcude other clouds

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#635]
Page: [Deleting a Cloud Volumes ONTAP working environment](https://docs.netapp.com/us-en/occm/task_deleting_working_env.html)

CVO Deletion warning only cites AWS. Should it be possible to re-word the message so other cloud users can refer to it?

Thanks.

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for reaching out.

I believe the deletion warning about termination protection is specific to AWS, but I've reached out to the product team to confirm.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

I updated the note on the page to generically state that we enable termination protection on Cloud Volumes ONTAP instances. It doesn't mention AWS specifically.

Thanks again for your feedback.

Regards,
Ben
