### ISSUE TITLE
Maximum working environment per connector

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#646]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/occm/concept_connectors.html)

There is no guidance about how many working environments we can create per connector. if there is a tested maximum, we should list it here so we can have good customer experience and avoid performance issues.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this issue. I've reached out to the team for guidance.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Hi again,

I've confirmed that there is no maximum number of working environments per Connector.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
We added a section to the docs about the number of working environments per Connector:
https://docs.netapp.com/us-en/occm/concept_connectors.html#number-of-working-environments-per-connector

Please let us know if you have any additional feedback.

Thanks again for reaching out.

Regards,
Ben
