### ISSUE TITLE
Could we add Cloud Sync data broker instance details?

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#654]
Not sure which will be the appropriate place but could we add each cloud data broker details for TCO calculation purposes and details?

Last time I checked was like this (but it may have changed):
AWS:   m5n.xlarge      - 4 vCPUs, 16GB RAM, Amazon Linux 2, 10GB HDD GP2
AZURE: Standard DS4 v2 - 8 vCpus, 28GB RAM, CentOS 7.7, 30GiB Premium SSD
GCP:   n1-standard-4   - 4 vCPUs, 15GB RAM, RHEL 7.7, 10GB HDD pd-standard

It could be added here:
Page: [Cloud Sync technical FAQ](https://docs.netapp.com/us-en/occm/faq_sync.html)

Or at each cloud page:
https://docs.netapp.com/us-en/occm/task_sync_installing_aws.html
https://docs.netapp.com/us-en/occm/task_sync_installing_azure.html
https://docs.netapp.com/us-en/occm/task_sync_installing_gcp.html

Regards,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for the suggestion, as well as the details. I've reached out to the engineering team to confirm. I'll let you know when this update is complete.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Gabriel,

I updated each cloud page by adding details about the data broker instance.

https://docs.netapp.com/us-en/occm/task_sync_installing_aws.html
https://docs.netapp.com/us-en/occm/task_sync_installing_azure.html
https://docs.netapp.com/us-en/occm/task_sync_installing_gcp.html

Thanks again for your feedback!
