### ISSUE TITLE
all VPCs can be either shared or non-shared VPCs

### ISSUE THREAD

**Issue by hananstrul** [NetAppDocs/occm#655]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

I got a request from GCP to clarify that each VPC can be shared or non-shared

**Comment by netapp-bcammett** [comment]
Hi Hanan,

Thank you for reaching out. I just want to clarify the request.

Are you saying that...

- For a single node system, the VPC can be either a shared VPC or non-shared VPC.
- For an HA pair, four VPCs are required. Each of those VPCs can be either shared or non-shared. For example, VPC-0 could be a shared VPC, while VPC-1, VPC-2, and VPC-3 could be non-shared VPCs

Thanks,
Ben

**Comment by hananstrul** [comment]
Hi Ben,

Correct.

Best,
Hanan

**Comment by netapp-bcammett** [comment]
Hi Hanan,

I updated the docs with the details that we discussed.

Thanks,
Ben
