### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/occm#658]
Page: [Creating a Connector from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors.html)

The link in the last bullet is broken (404) - Creating a Connector in AWS for FSx for ONTAP

**Comment by netapp-bcammett** [comment]
Hi Phoebe,

Thank you for catching this issue.

@juliantap, can you please remove the last link from the page?

Thanks,
Ben

**Comment by juliantap** [comment]
Thanks again, Phoebe. I removed the erroneous link.
