### ISSUE TITLE
Request for dates for new releases

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/occm#66]
Page: [What’s new in Cloud Manager 3.5](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

Is it possible to have New Features/Updates assigned to a month of release as well as just the release of OCCM/CVO? e.g. SaaS Backup documentation: 
![2018-08-07_10h53_07](https://user-images.githubusercontent.com/2746488/43747929-15fc4d46-9a30-11e8-94a4-3123765e1a83.png)
 https://docs.netapp.com/us-en/saasbackupO365/reference_new_saasbackupO365.html

**Comment by netapp-bcammett** [comment]
Thank you for the suggestion. I added the release date next to the release number on the What's new page.
