### ISSUE TITLE
When "Convert an Eval license to BYOL" is performed on CVO HA for Azure, CVO nodes automatically restarted.

### ISSUE THREAD

**Issue by yumyan** [NetAppDocs/occm#660]
Page: [Manage licenses for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_managing_licenses.html)

Could you please add a note about automatically restart(takeover, giveback) to the paragraph "Convert an Eval license to BYOL"?

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this feedback.

We do have a note that this requires a restart of single node systems:

![image](https://user-images.githubusercontent.com/18287750/132346061-43281b69-6320-4f4e-aaa9-9c3205d3f433.png)

But it sounds like you're suggesting that it also restarts an HA pair, which initiates takeover and giveback. Is that right?

Thanks,
Ben

**Comment by yumyan** [comment]
Yes,
And I experienced when I converted the license, HA pair Nodes takeover / giveback immediately.

I thought the note of "requires a restart" is to perform myself.
But, it is automatic.

**Comment by netapp-bcammett** [comment]
Hi again,

I confirmed that Cloud Manager does in fact restart an HA pair, so I updated the docs to describe this behavior. I also clarified that Cloud Manager restarts the system. You don't need to do it yourself.

You can find the updates here:
https://docs.netapp.com/us-en/occm/task_managing_licenses.html#convert-an-eval-license-to-a-byol

Please let us know if any additional changes are needed.

Thanks again for your help!

Regards,
Ben
