### ISSUE TITLE
Request for update docs for FSxO 

### ISSUE THREAD

**Issue by Dariukuss** [NetAppDocs/occm#666]
Page: [Create and manage volumes for Amazon FSx for ONTAP](https://docs.netapp.com/us-en/occm/task_manage_fsx_volumes.html)

Hey !! Not really an issue but maybe we can add new page on the FSx ONTAP setup pages to explain networking as it is on the CVO one: 
https://docs.netapp.com/us-en/occm/reference_security_groups.html#rules-for-cloud-volumes-ontap

something like this image I think would be great for customers to understand better: 

![image](https://user-images.githubusercontent.com/45126082/132691501-0a301189-06e2-4a39-b98b-fddd0bb0ae77.png)

Thanks team - You are the best !!

**Comment by netapp-bcammett** [comment]
@Dariukuss, thank you for submitting this feedback. We appreciate it.

@juliantap, can you please take a look and respond?

**Comment by juliantap** [comment]
Thanks you @Dariukuss! I will speak to the development team and see what we can create to fit the bill.

**Comment by juliantap** [comment]
@Dariukuss just wanted to give an update. The engineering team is working on this request and I'll publish a diagram as soon as it's available. Please let me know if you have any questions or additional requests. Thanks!

**Comment by Dariukuss** [comment]
Thanks Julia, team ¡

That’s great ¡!

Darío López Portilla
Cloud Solutions Engineer
(+34) 603 62 86 69

NetApp
***@***.******@***.***>

[A picture containing bird    Description automatically generated]<https://www.netapp.com/us/index.aspx>

**Comment by juliantap** [comment]
Hi @Dariukuss, sorry for the delay on this--you probably thought I'd forgotten you! 

To prevent duplication of content, we will add a link to the AWS networking diagram (https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/self-manage-prereqs.html) and port information. This change will be published in an upcoming batch of changes & I'll update this ticket when it's live. 

Thank you again for your feedback (and patience!),

Julia
