### ISSUE TITLE
Link is giving me a 404 error 

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/occm#670]
Page: [Getting started checklist](https://docs.netapp.com/us-en/occm/reference_checklist_cm.html)

This link is giving me an 404 error 

[Data backup from ONTAP clusters to Amazon S3 or Azure Blob storage](https://docs.netapp.com/us-en/occm/task_backup_from_onprem.html)

**Comment by netapp-tonacki** [comment]
Thanks Ben.  I broke that topic into multiple topics and forgot that there is this link in Getting Started.  I'll update that, and make some other changes, after v2 is done.

Tom

**Comment by netapp-tonacki** [comment]
I have updated the links in the Getting Started to fix that bad link and to break out Tiering and Backup sections.  Thanks, Ben
