### ISSUE TITLE
VPCs the connector needs access to

### ISSUE THREAD

**Issue by okrause** [NetAppDocs/occm#680]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

"If you’re deploying an HA pair, then the Connector needs a connection to all four VPCs."

The statement that the connector needs a connection to all four VPCs in wrong, IMHO. It only needs access to VPC-0.

**Comment by netapp-bcammett** [comment]
Hi Oliver,

Thank you for reaching out with this feedback. I just sent a message off to the engineering team, which is where this information came from. I'll let you know what I hear.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Yes, I confirmed that the Connector only requires connectivity to VPC-0. I'll update the docs to fix this.

**Comment by netapp-bcammett** [comment]
The docs have been updated. Thanks again!

Ben
