### ISSUE TITLE
Adding Azure credentials to Cloud Manager for Paygo only?

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/occm#681]
Page: [Managing Azure credentials and subscriptions for Cloud Manager](https://docs.netapp.com/us-en/occm/task_adding_azure_accounts.html)

Is the section titled "Adding Azure Credentials to Cloud Manager" only applicable with Pay-go subscribers? If so, could we make note of that near the top of the section?

**Comment by netapp-bcammett** [comment]
Hi there,

Thanks for providing this feedback. Adding Azure credentials to Cloud Manager is only applicable if you want to deploy Cloud Volumes ONTAP in different Azure accounts. It's not specific to PAYGO.

Some background:

> When you deploy a Connector from Cloud Manager, Cloud Manager enables a system-assigned managed identity on the virtual machine, creates a custom role, and assigns it to the virtual machine. The role provides Cloud Manager with permissions to manage resources and processes within that Azure subscription. Cloud Manager selects these Azure credentials by default when you create a new working environment for Cloud Volumes ONTAP.
> 
> If you want to deploy Cloud Volumes ONTAP in different Azure accounts, then you need to provide the required permissions and add the credentials to Cloud Manager.

This information is in the docs, but it's not clearly stated in the section that you're referring to. I'll update that section to fix this.

Thanks again for submitting your feedback.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I updated the docs to more clearly state when Azure credentials should be added to Cloud Manager. 

Please take a look at the section titled "Adding additional Azure credentials to Cloud Manager" and let me know if any additional clarification is needed.

Thanks again,
Ben
