### ISSUE TITLE
ILB is missing from the networks/VPC picture

### ISSUE THREAD

**Issue by okrause** [NetAppDocs/occm#683]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

The picture which shows the VPCs and the ILBs only shows 3 ILBs. A CVO HA system has 4 ILBs. The SVM Management ILB is missing. Add another ILB box for SVM Management.

**Comment by netapp-bcammett** [comment]
Hi Oliver,

Starting with Cloud Volumes ONTAP 9.9.0, Cloud Manager creates three internal load balancers. The SVM management LIF is no longer created by default.

Regards,
Ben

**Comment by okrause** [comment]
Hmmm, the documentation (and real test in LoD) show that it gets created by default, but can be disabled by using API calls (not OCCM UI): https://docs.netapp.com/us-en/occm/reference_networking_gcp.html#requirements-for-cloud-volumes-ontap

**Comment by netapp-bcammett** [comment]
@felix-melligan, can you please confirm that only 3 internal load balancers are created when deploying Cloud Volumes ONTAP in Google Cloud?

**Comment by felix-melligan** [comment]
@netapp-bcammett it was pulled from 9.9, but I've been told will be in 9.10.1. Probably worth taking it out. There are currently still 4 backend services

**Comment by netapp-bcammett** [comment]
I updated the text and graphic to list four internal load balancers for an HA pair in Google Cloud.

Thanks again for submitting this issue.

Regards,
Ben
