### ISSUE TITLE
URL for NSS activation is down

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#689]
Page: [Manage licenses for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_managing_licenses.html)

Hello team.

In the following lines the NSS URL is not working, thanks for taking care.

What you’ll need
You need to provide Cloud Manager the serial number of the license or the license file.

If you want to enter the serial number, you first need to add your NetApp Support Site account to Cloud Manager. This is the NetApp Support Site account that’s authorized to access the serial number.

**Comment by netapp-bcammett** [comment]
Thank you for reporting this issue. The link is now fixed.

Thanks again,
Ben
