### ISSUE TITLE
the app.conf file also supports subscription

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#691]
Page: [Using an Azure Private Link with Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_enabling_private_link.html)

the engineering team added another option where you can add the subscription of the Private DNS Zone if it exists in a different subscription than your Connector.

Here is an example:

"user-private-dns-zone-settings" : {
    "resource-group" : "blob-zone-prod-eastus2-rg",
    **"subscription" : "aa1ec145-4b77-436f-a4a3-443248c4d12e",**
    "use-existing" : true
}

**Comment by netapp-bcammett** [comment]
Hi Richard,

Thank you for reaching out with this information.

If the Private DNS Zone is in the same subscription, then you would just omit the "subscription" field from app.conf?

Thanks,
Ben

**Comment by nichollri** [comment]
Yes.  It is only needed if it is a different subscription.

**Comment by netapp-bcammett** [comment]
I added the subscription parameter to the docs.
https://docs.netapp.com/us-en/occm/task_enabling_private_link.html#providing-cloud-manager-with-details-about-your-azure-private-dns

Thanks again for letting us know about this new parameter.

Regards,
Ben
