### ISSUE TITLE
Add details regarding SSL Decryption

### ISSUE THREAD

**Issue by mnicolase** [NetAppDocs/occm#692]
SSL decryption is not support in Cloud Manager. Multiple customers are trying to enable it and are requesting documentation stating it is not supported

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for taking the time to submit this issue. Please pardon my ignorance: could you specify a little more detail about how a customer is trying to set up SSL decryption with Cloud Manager? What goal are they trying to achieve, and how exactly are they trying to enable it?

Thanks,
Ben

**Comment by mnicolase** [comment]
Hi Ben,

For enhanced security, customers are tempted to enabled SSL decryption/inspection in their Firewall. Since it is not supported, they are getting error messages in Cloud Manager and the connector instance shows as inactive.

For enhanced security, they have the option to install a CA (which is documented)

Since there are no mention of SSL decryption not being supported for Cloud Manager in the documentation, customers are enabling this feature in their Firewall and end up opening cases to have us fix it. The most recent customer is requesting for documentation stating that SSL decryption is indeed not supported for CM, unfortunately, it is not mentioned anywhere in the docs

Nick Maloizel
Technical Support Engineer 3
TSC / CSD
***@***.******@***.***>

[Graphical user interface, application  Description automatically generated]<https://www.youracclaim.com/badges/e825978e-5b73-4d1a-8e42-c7f19cea099d/public_url>[A close up of a sign  Description automatically generated]<https://www.youracclaim.com/badges/0b7938c8-6d54-4da0-9698-59e37e42110b/public_url>[A white sign with black text  Description automatically generated with low confidence]<https://www.credly.com/badges/704b509d-30d9-476d-9740-476876f8711b>

[A picture containing text, clipart  Description automatically generated]<https://insight.netapp.com/>


***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>

**Comment by netapp-bcammett** [comment]
Perfect. Thank you! We'll have this information in the docs by tomorrow at the latest.

**Comment by mnicolase** [comment]
Awesome! Thank you very much


Nick Maloizel
Technical Support Engineer 3
TSC / CSD
***@***.******@***.***>

[Graphical user interface, application  Description automatically generated]<https://www.youracclaim.com/badges/e825978e-5b73-4d1a-8e42-c7f19cea099d/public_url>[A close up of a sign  Description automatically generated]<https://www.youracclaim.com/badges/0b7938c8-6d54-4da0-9698-59e37e42110b/public_url>[A white sign with black text  Description automatically generated with low confidence]<https://www.credly.com/badges/704b509d-30d9-476d-9740-476876f8711b>

[A picture containing text, clipart  Description automatically generated]<https://insight.netapp.com/>


***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>

**Comment by netapp-bcammett** [comment]
As discussed, I added SSL decryption to the known limitations section of the release notes.

https://docs.netapp.com/us-en/occm/reference_limitations.html

Thanks again for opening this issue.

Regards,
Ben
