### ISSUE TITLE
Could be possible to correct the link and add ports information?

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#696]
Page: [Create an Amazon FSx for ONTAP working environment](https://docs.netapp.com/us-en/occm/task_creating_fsx_working_environment.html)

Hello team. In this URL the link called "discover it using Cloud Manager." is not working.

I also detected that Cloud Manager customers really appreciate to have more information on how to configure ports in AWS SG to allow access from Snapmirror ONTAP on-prem and the ports need from Cloud Manager also to manage FSx for ONTAP from Cloud Manager itself.

Thanks so much.

**Comment by jsuarezs** [comment]
Hello @juliantap. Thanks for correcting the link.

I would find useful for customers using Cloud Manager that they need to open 443 HTTPS port in order to manage FSx for ONTAP from Cloud Manager, it will be useful then link this URL ports specific for FSx for ONTAP, like a short table like that for FSx for ONTAP in this case.

Best,
Javi.

**Comment by juliantap** [comment]
Thank you, @jsuarezs. Let me check with engineering and see if there's something specific we can add for FSx. 

Thanks!

J

**Comment by juliantap** [comment]
Hi @jsuarezs -- I promise I haven't forgotten about you! I am working on final approval for the port information. A new topic with FSx specific ports will be included in an update soon. I will update you here when it is live. 

Thank you again for your feedback--and patience!

Julia

**Comment by juliantap** [comment]
Hi @jsuarezs, I am merging the changes with the new security ports topic now. Thank you for your feedback and patience!
