### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#697]
Page: [Creating a Connector in AWS from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html)

Hello team.

The link in the phrase: "For IAM user permissions for Amazon FSx for ONTAP, see Create an FSx for ONTAP working environment." is not working at all.

Thanks for correcting this one.

**Comment by juliantap** [comment]
Hi @jsuarezs! I will check and correct this morning. Thank you again! 

J
