### ISSUE TITLE
Incorrect order of on-prem connector install steps for GCP   

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#701]
Page: [Installing the Connector software on an existing Linux host](https://docs.netapp.com/us-en/occm/task_installing_linux.html)

Customer, ASML, in case 2008935534 had problems after installing the connector software on-prem as he could not access it.
The resolution was that before continuing with step 7, skip to the GCP part of "After you finish"

**So step 7 should be:**
  • GCP: Set up a service account that has the permissions that Cloud Manager needs to create and manage Cloud Volumes ONTAP systems in projects.

**And then:**

  After you log in, set up Cloud Manager:
  a. Specify the Cloud Central account to associate with the Connector.
  
  Learn about Cloud Central accounts.
  
  b. Enter a name for the system.

**Comment by netapp-bcammett** [comment]
Thanks for your feedback! I updated the docs by moving the Google Cloud info to step 7.

Regards,
Ben
