### ISSUE TITLE
Please review Persistent disks types for GCP default config

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#717]
Page: [Default configuration for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/reference_default_configs.html)

Hi, the default configuration disks looks to be wrong.
I have deployed a 9.10 CVO HA and with the exception of Core disk, all were SSD Persistent Disks:

---This is correct---------
GCP
    One 10 GiB SSD persistent disk for boot data
    One 64 GiB SSD persistent disk for root data
    One 500 GiB SSD persistent disk for NVRAM
    One 315 GiB Standard persistent disk for saving cores
    One GCP snapshot each for the boot disk and root disk

For an HA pair, there are two disks per node for root data.
---------END---
I am attaching an screen shot of one of the nodes.

![image](https://user-images.githubusercontent.com/34706481/137456613-93e2573b-c848-4be5-af02-2a13c0d9f355.png)

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for letting me know. I'll confirm the right disk type and sizes and get this updated.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Gabriel,

I updated the page to list the latest default disk sizes for Cloud Volumes ONTAP in Google Cloud. As you'll see, there's now one section for single node and a separate section for HA pairs to make this clear.

https://docs.netapp.com/us-en/occm/reference_default_configs.html#google-cloud-single-node

Thanks,
Ben
