### ISSUE TITLE
the UI is not the latest 3.9.11 one ! how can i add a K8S cluster (e.g. Tanzu easily into cloud manager)?

### ISSUE THREAD

**Issue by calvinwonghk** [NetAppDocs/occm#722]
Page: [Using Cloud Volumes ONTAP as persistent storage for Kubernetes](https://docs.netapp.com/us-en/occm/task_connecting_kubernetes.html)

**Comment by netapp-bcammett** [comment]
Hi again,

Just wanted to check back to see if you could answer the question in my previous comment.

Thanks,
Ben
