### ISSUE TITLE
Request for detailing the procedure of connector ASUP download and send

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/occm#724]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/occm/task_managing_connectors.html)

Section 
Downloading AutoSupport messages (usually directed by NetApp personnel when you have issues)

Currently a KB exists for the same - https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_gather_Cloud_Manager_Connector_(OCCM)_logs_from_the_GUI

But it is better documented in product document as KB for manually collecting logs makes sense.
https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_manually_collect_Cloud_Manager_logs

The UI should also indicate a label "Download ASUP) near the ASUP download symbol for connector.

**Comment by netapp-bcammett** [comment]
Hi Aneesha,

A section was added to the docs for downloading or sending an AutoSupport message from the Connector:
https://docs.netapp.com/us-en/occm/task_managing_connectors.html#downloading-or-sending-an-autosupport-message

Apologies for the delay. Thanks again for reaching out.
