### ISSUE TITLE
CVO for AWS internal disks default configurations 

### ISSUE THREAD

**Issue by ykotake15** [NetAppDocs/occm#725]
Page: [Default configuration for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/reference_default_configs.html)

Hi, the default configuration disks looks to be wrong.
I have deployed a 9.10 CVO AWS(HA-Pair) and it seems following configurations.

Two root disks and one boot disk per node:
9.10: 45 GiB io1 disk for boot data and a 140 GiB gp3 disk for root data

I am attaching an screen shot.
![image](https://user-images.githubusercontent.com/93212224/138919583-8a437fec-f6d2-4a16-85ec-7d74bafc4113.png)

**Comment by netapp-bcammett** [comment]
Thank you for confirming. I have confirmed that the default disks don't match what's currently in the docs, but they also don't match the internal lab on demand deployment. I asked a few follow up questions and hope to get this finalized soon.

**Comment by ykotake15** [comment]
Thank you for your update.
If possible, my customer is asking for the default configurations, so it is helpful to provide the deployment configuration from marketplace before updating the document.

**Comment by netapp-bcammett** [comment]
Thank you. I've followed up with my contacts in engineering again. I'm waiting for answers to a few questions.

**Comment by netapp-bcammett** [comment]
Hi Yuki,

I confirmed the correct disk sizes (they do match what you're seeing in lab on demand) and updated the docs accordingly.
https://docs.netapp.com/us-en/occm/reference_default_configs.html#aws

Thank you again for reaching out with your feedback.

Regards,
Ben

**Comment by ykotake15** [comment]
Hi Ben,

Thank you for your update!

Best regards,
Yuki
