### ISSUE TITLE
"The nodes' intercluster LIFs are able to access the internet." is a requirement?

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/occm#738]
Page: [Backing up on-premises ONTAP data to StorageGRID](https://docs.netapp.com/us-en/occm/task_backup_onprem_private_cloud.html)

I find below in Cloud Backup Documentation.
"The nodes' intercluster LIFs are able to access the internet."
Is this a requirement?
If it is a requirement, I think it would limit the environment in which it could be used.
Could you please kindly check this is necessary or not.

Best regards,

**Comment by netapp-tonacki** [comment]
Hi imasafum,  Thanks for your comment.  I see what you mean in case the StorageGRID is in the same on-prem location as the cluster and may not need internet to make the connection.  I'll check on this and let you know what I hear.

Thanks, Tom

**Comment by imasafum** [comment]
Hi Tom,

Yes, exactly.
Thank you for your support.

Masafumi,
