### ISSUE TITLE
Could you kindly please add port requirements for On-Premise Cloud Connector?

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/occm#741]
Page: [Networking requirements for the Connector](https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html)

I'd like to clarify port requirements for On-Premise Cloud Connector.
So could you kindly please consider to add port requirements for On-Premise Cloud Connector in the Ports and security groups section?

Best regards,

**Comment by netapp-bcammett** [comment]
Thank you for reaching out with this feedback. I updated the page by adding the ports used by the Connector on an on-premises Linux host.

Thanks again,
Ben
