### ISSUE TITLE
connector host requirements may have changed

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#749]
Page: [Connector host requirements](https://docs.netapp.com/us-en/occm/reference_cloud_mgr_reqs.html)

We have been provided a script from engineering that checks cloud provider endpoint connectivity and host requirements.

When I run it on a newly deployed connector VM in Azure, I will get the following message stating that there were potential changes to cpu, ram and space requirements. Creating this doc burt to double check and correct the info or the script as needed:

[lgabor@lgaborConnector ~]$ ./netapp_cloud_site_survey_tool.sh azure

*********************************
NetApp Cloud Site Survey Tool
*********************************

use --help for details and execution options

[+] Validating System Prerequisits

ERROR: Memory is below minimal 62000000 (KB) requirement

ERROR: 4 CPUs is less than minimal requirement of 8

ERROR: Available disk space is less than minimal 102000000 KB requirement

OS version validation passed

**Comment by netapp-tonacki** [comment]
Hi laagabi,  If I look at the script I see:
if [ $MODE == "ds" ]; then
  MIN_MEMORY=62000000 # KB, ~60 GB
  MINIMAL_CORES=8
  MINIMAL_DISK=102000000 # KB, ~100 GB
  RHEL_8_SUPPORTED=1
elif [ $MODE == "cm" ]; then
  MIN_MEMORY=14000000 # KB, ~14 GB
  MINIMAL_CORES=4
  MINIMAL_DISK=102000000 # KB, ~100 GB

I think you may need to add "-m cm" if you are checking the Connector. The Connector settings listed above exactly match what we have in the [docs](https://docs.netapp.com/us-en/occm/reference_cloud_mgr_reqs.html).

Thanks, Tom

**Comment by laagabi** [comment]
Hi Tom,

Indeed.. apologies for jumping into conclusions 😊

Was the heat of the moment since I was simultaneously on a p1 where we actually had problems with the storage space hence got a bit nervous about it and failed to read the script properly:

   # Display Help
   echoyellow "Data Sense site survey tool"
   echo "tool checks prerequistis such as CPU, RAM, Disk, OS features, URL connrecity and more"
   echo
   echoyellow "Syntax: ./netapp_cloud_site_survey_tool.sh [-p|h|m cm/ds]"
   echo "options:"
   echo "-p, --provider     Choose relevant provider aws/azure/gcp/onprem - default onprem"
   echo "-m, --mode         Choose relevant service mode cm- cloud manager/ ds- data sense - default ds"
   echo "-h, --help         Print this Help."
   echo
}


With the “-m cm” option it will work, though, It still complains about the disk size. I assume that this is because sda2 is only 99.5g due to a 500m chunk being reserved for /boot
@Aneesha ***@***.***>, @Dahan, ***@***.***> can maybe engineering fine tune this?



***@***.*** lgabor]# ./netapp_cloud_site_survey_tool.sh -m cm -p azure

*********************************
NetApp Cloud Site Survey Tool
*********************************

use --help for details and execution options

[+] Validating System Prerequisits

Memory validation passed

CPU validation passed

ERROR: Available disk space is less than minimal 102000000 KB requirement

OS version validation passed

[+] Testing firewalld
Firewalld is disabled


[+] Testing Cloud Manager (azure) URL connectivity
Connected to https://management.azure.com successfully
Connected to https://login.microsoftonline.com successfully
Connected to https://management.microsoftazure.de successfully
Connected to https://login.microsoftonline.de successfully
Connected to https://management.usgovcloudapi.net successfully
Connected to https://login.microsoftonline.com successfully
Connected to https://api.services.cloud.netapp.com successfully
Connected to https://cognito-idp.us-east-1.amazonaws.com successfully
Connected to https://cognito-identity.us-east-1.amazonaws.com successfully
Connected to https://sts.amazonaws.com successfully
Connected to https://cloud-support-netapp-com-accelerated.s3.amazonaws.com successfully
ERROR: Failed to connect to https://cloudmanagerinfraprod.azurecr.iof 000
Connected to https://kinesis.us-east-1.amazonaws.com successfully
Connected to https://cloudmanager.cloud.netapp.com successfully
Connected to https://netapp-cloud-account.auth0.com successfully
Connected to https://mysupport.netapp.com successfully
Connected to https://support.netapp.com successfully
Connected to https://cloud-support-netapp-com-accelerated.s3.us-west-1.amazonaws.com successfully
Connected to https://ipa-signer.cloudmanager.netapp.com successfully


***@***.*** lgabor]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk
sda      8:0    0  100G  0 disk
├─sda1   8:1    0  500M  0 part /boot
└─sda2   8:2    0 99.5G  0 part /
sdb      8:16   0   28G  0 disk
└─sdb1   8:17   0   28G  0 part /mnt/resource


BR,
Gabor.

**Comment by netapp-bcammett** [comment]
Going to go ahead and close this one.
