### ISSUE TITLE
No wait list anymore for ANF

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/occm#753]
Page: [Setting up and discovering Azure NetApp Files](https://docs.netapp.com/us-en/occm/task_manage_anf.html)

As ANF is now available for all customers, I think this phrase can be deleted: 
"Requesting access
You need to be granted access to Azure NetApp Files by submitting an online request. You’ll need to wait for approval from the Azure NetApp Files team before you can proceed."

https://azure.microsoft.com/en-us/blog/the-wait-list-is-over-azure-netapp-files-is-enterpriseready-in-your-azure-portal/

Best
Holger

**Comment by netapp-tonacki** [comment]
Hi Holger,  Thanks for letting us know about this change.  I see it announced [here ](https://www.netapp.com/blog/ungated-innovation-azure-netapp-files/) thru NetApp too.  What you suggest sounds like the right thing to do, but I'd like to touch base with the Product Manager just to make sure.

I'll let you know what I hear.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Holger,  I heard back, and yes we should we remove this.  I'll delete it from the docs today.  Thanks again for bringing this to our attention.

Thanks, Tom
