### ISSUE TITLE
Description regarding the support of CM connector in the AWS Osaka region

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/occm#756]
Page: [What’s new in Cloud Manager 3.9](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

Hi team,
It seems that CM connector in AWS Osaka region is supported.
This enhancement is very important for Japanese customers and partners.
Therefore, could you please add the description of this important enhancement in the release note?

**Comment by kmakoto-at-netapp** [comment]
Thank you Ben,  I look forward to your reply.

**Comment by netapp-bcammett** [comment]
Hello,

I just received confirmation that we do support the the Japan-Osaka region (ap-northeast-3) in AWS. 

Someone from the cloud team will update this page: https://cloud.netapp.com/cloud-volumes-global-regions

I will update the "what's new" section in the release notes later today with this information.

Thank you for reaching out.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
The Global Regions Maps page on Cloud Central was updated to include Osaka. I also updated the "what's new" section in the Cloud Manager docs.

https://cloud.netapp.com/cloud-volumes-global-regions

Thanks again,
Ben
