### ISSUE TITLE
Which disk type is used for NVRAM disk of CVO for AWS.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/occm#759]
Page: [Cloud Volumes ONTAP のデフォルト設定](https://docs.netapp.com/ja-jp/occm/reference_default_configs.html)

Hi, in this page, disk type for NVRAM disk are written about Azure and Google Cloud.
But no mentioned about CVO for AWS.
So could you kindly please to update about disk type for CVO AWS? 
Best regards,

Masafumi,

**Comment by netapp-bcammett** [comment]
Hi Masafumi,

Thank you for reaching out with this question. I don't believe Cloud Manager purchases an EBS disk for NVRAM in AWS, but I've sent a question off to the lead engineer to confirm. Whether the answer is yes or no, I'll update that page to provide clarification.

Thank you again for your feedback.

Regards,
Ben

**Comment by imasafum** [comment]
Hi Ben-san,

Thank you for your support.
In my understanding, only some instance types are supported NVMe.
So I think It would be better to clarify which storages is allocated to NVRAM for AWS instance type.

Thank you so much for your time.
Best regards,

Masafumi,
