### ISSUE TITLE
Question about supporting S3 compatible storage.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/occm#760]
Page: [Cloud Backup の詳細をご確認ください](https://docs.netapp.com/ja-jp/occm/concept_backup_to_cloud.html)

To whom it may concern,

Many customer asked about supporting S3 compatible storage.
So I think it's better to mention about our how support (or not) for S3 compatible storage with CBS.
Could you kindly please to consider to write about this topic?

Best regards,

Masafumi,

**Comment by netapp-tonacki** [comment]
Hi Masafumi,  Thanks for your suggestion.  We don't typically list things we don't support in the documentation.  Do you have any idea why we are getting people asking about this now?

I have asked the product manager to get his opinion about listing a storage platform that we don't support.

I'll let you know what I hear.  Thanks, Tom

**Comment by imasafum** [comment]
Hi Tom-san,

Thank you for your support.
I think there are many of Cloud Storage Service and usually these are S3 compatible.
So customer will have expectation that supporting S3 means S3 compatible storage (service) is also supported (or worked)?
I think It's better that we note that our support stance for S3 compatible storage.

And by the way, could you please confirm with Product Manager if we apply FPVR for specific S3 compatible storage and if it will be officially supported?

Thank you very much for your time.
Best regards,

Masafumi,

**Comment by netapp-tonacki** [comment]
Hi Masafumi, The PM agrees we should just list what we support: Cloud providers and StorageGRID.  If we don't mention S3-compatible, then we don't support it.  You would have to check with him about specific FPVRs.  Email me directly so we can take this conversation off of GitHub.

Thanks, Tom
