### ISSUE TITLE
Add direct link to Roles?

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#766]
Page: [Account settings: users, workspaces, Connectors, and subscriptions](https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html)

It seems like we should have a link to a description of the permissions for the roles on this page.

https://docs.netapp.com/us-en/occm/reference_user_roles.html

Took me a while to find it when I was on with a customer, just felt like when we are describing what these things are it would be helpful to have a link to get to the more detailed information of the permissions they provide.

**Comment by netapp-bcammett** [comment]
Hi Richard,

Yes, there should be a link. We'll get that added.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Done!

Thanks again for reaching out.

Regards,
Ben
