### ISSUE TITLE
Clarification request on 3.9.13 enhancement statement

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/occm#768]
Page: [What’s new in Cloud Manager 3.9](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

Specifically here: https://docs.netapp.com/us-en/occm/reference_new_occm.html#cloud-manager-3-9-13-28-nov-2021 it is stated "Ports 8023 and 49000 are no longer open on Cloud Volumes ONTAP systems in Azure for both single node systems and HA pairs."  

This is great news!

What is not clear to me is whether or not older deployments are somehow updated, **or** if this would only apply for new Azure SN/HA deployments created while running 3.9.13 or later.

Thank you.

**Comment by netapp-bcammett** [comment]
Hi Steve,

I'm checking on that and will update the docs as soon as I have clarification.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Steve,

Older deployments are not updated. I'll clarify this in the docs and let you know when that's done.

Thanks,
Ben

**Comment by definitelynotsteve** [comment]
Thank you very much, Ben!!
-Steve


Stephen Weller
CloudTAM

NetApp
Mobile Phone: +1 919.395.5598
Desk Phone: +1 919.476.8732
***@***.******@***.***>

NetApp Technical Support:

US:               888 463 8277
EMEA:          00800 4463 8277
ASIA:            800 800 80 800

*Ask to speak with the Duty Manager if you require a higher level of support
Out of office hours SAM/CloudTAM assistance for Priority 1 and other urgent support issues:

Phone:   +1 929 251 9200
E-mail:    ***@***.******@***.***>

You may also get Support on the web at:
http://mysupport.netapp.com<http://mysupport.netapp.com/>

Upcoming OOTO: December 20 – December 31

**Comment by netapp-bcammett** [comment]
The release notes were updated. Thanks again for submitting this issue!

Regards,
Ben
