### ISSUE TITLE
Clarity on unused node based BYOL

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#786]
Page: [Viewing unused Cloud Volumes ONTAP licenses](https://docs.netapp.com/us-en/occm/task_managing_ontap.html#viewing-unused-cloud-volumes-ontap-licenses)

Hi Ben,

can we please add a clarity that BYOL license clock ticks right on day1 on the following calendar month? with today's documentation, customers might think that they can enable or use the license whenever they want.

An added clarity can help to activate the unused CVO serials as well.

**Comment by netapp-bcammett** [comment]
Hi there,

Thanks for reaching out. Can you please clarify what you mean by this:

> can we please add a clarity that BYOL license clock ticks right on day1 on the following calendar month?

For example, if you buy a node-based BYOL license on Dec 15, 2021, the start of the licensing term is Jan 1, 2022 (the first day of the next month).

Is that what you mean?

Thanks,
Ben

**Comment by sabarig84** [comment]
Hi Ben, that is correct. :)

**Comment by netapp-bcammett** [comment]
I updated the page with a note about when the license term starts.

Thanks again,
Ben
