### ISSUE TITLE
outdated link to cloud manager policy

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#787]
Page: [Creating a Connector in Azure from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html)

The link in text "...create your own **using this policy**. " contains an outdated version of the cloud manager operator role:
>>> https://occm-sample-policies.s3.amazonaws.com/Policy_for_cloud_Manager_Azure_3.9.8.json

VS the current one that can be obtained from https://mysupport.netapp.com/site/info/cloud-manager-policies
>>> https://occm-sample-policies.s3.amazonaws.com/Policy_for_cloud_Manager_Azure_3.9.12.json

**Comment by netapp-bcammett** [comment]
Thank you for pointing this out. I'm working on the fix right now. I'll let you know when the changes are done.

**Comment by netapp-bcammett** [comment]
The doc changes are complete. Thanks again for pointing this out.

Thanks,
Ben
