### ISSUE TITLE
If steps are followed, user is not prompted for proxy config

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/occm#793]
Page: [Install the Connector on an existing Linux host that has internet access](https://docs.netapp.com/us-en/occm/task_installing_linux.html)
--
The following statement seems to be incorrect per my customer:

4. Unless you specified the silent parameter, type Y to continue the script, and then enter the HTTP and HTTPS ports when prompted.

Here is the clarification I requested and his response:

--Question--
Hi <customer>,

Can you please confirm that the step from the following link that was incorrect is the highlighted one?
https://docs.netapp.com/us-en/occm/task_installing_linux.html#install-the-connector

I believe you said that the issue was that if you followed the steps you were never prompted for the proxy information.  Due to this you had to break out of the script and re-run it with the proxy information provided in-line.

With your confirmation we’ll get this fixed.

--Response--
That is correct.  I did not specify silent and I never got prompted for the proxy information.

Please let me know if you have questions.
Thanks!

**Comment by netapp-bcammett** [comment]
Hi Steve,

The proxy information needs to be specified in the command parameters, like shown in step 3:

> ./OnCommandCloudManager-V3.8.13.sh [silent] [proxy=ipaddress] [proxyport=port] [proxyuser=user_name] [proxypwd=password]

The installer doesn't prompt you to provide proxy details.

The ports in step 4 are for the HTTP and HTTPS ports for the Connector (the ports for connecting to the local UI). Was the customer not prompted for those ports?

Thanks,
Ben

**Comment by definitelynotsteve** [comment]
Thanks for the clarification!  I am checking with the customer on these details and will get back to you once I have the response.  

Best,
Steve

**Comment by definitelynotsteve** [comment]
Thanks again for the clarification.  I asked my customer if they were prompted for HTTP/HTTPS and he said no.  I then decided to test myself (I don't have a proxy) to see what the procedure looks like.  I did not see any prompts to ask for non-default HTTP/HTTPS ports.

[cmadmin@rollownconnector ~]$ ./OnCommandCloudManager-V3.9.13.sh
Verifying archive integrity...  100%   All good.
Uncompressing ServiceConnector-V3.9.13  100%
Starting Installation Thu Jan  6 17:47:28 UTC 2022 Log File: /tmp/install_01062022_17_47_28.log
OS Version Ok Continue installation....
Welcome To The NetApp Service Connector Installation Wizard

This will install NetApp Service Connector 3.9.13 on your computer

Type 'Y' to continue or 'N' to exit setup: y
wget already installed
***** Installing Java 1.8 *****
net.ipv6.conf.all.disable_ipv6 = 1
***** Installing Service Connector *****
Preparing...                          ########################################
Updating / installing...
service_connector-3.9.13-23           ########################################
Created symlink from /etc/systemd/system/multi-user.target.wants/service-manager.service to /usr/lib/systemd/system/service-manager.service.
***** Starting Docker Installation *****
Error: Package: glibc-2.17-292.el7.i686 (local)
           Requires: glibc-common = 2.17-292.el7
           Installed: glibc-common-2.17-307.el7.1.x86_64 (@anaconda/7.8)
               glibc-common = 2.17-307.el7.1
           Available: glibc-common-2.17-292.el7.x86_64 (local)
               glibc-common = 2.17-292.el7
Warning: RPMDB altered outside of yum.
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
Docker is running
***** Starting Service Connector *****
***** Installation Finished Thu Jan  6 17:49:51 UTC 2022 *****

 - You can now access NetApp Service Connector by browsing to this machine.
   To access NetApp Service Connector from a different machine,
 just use http://<SERVER_IP>

 - You can use the Netapp OnCommand Cloud Manager rest APIs by accessing
 http://<SERVER_IP>/occm/api-doc

 - The AutoSupport feature is enabled by default (recommended).
***** Waiting For Web Server to be up *****
................
***** Web Server is up *****
[cmadmin@rollownconnector ~]$


Additionally, if we can make it any more clear that the proxy information must be entered as command parameters, that may be helpful too.

Thanks!

**Comment by netapp-bcammett** [comment]
Thank you for providing these details. And perfect timing--I'm about to push out a doc update and will include the required updates for what you just found. I'll let you know when it's done.

**Comment by netapp-bcammett** [comment]
Hi Steve,

I added a statement about specifying the proxy parameters and I removed the step about changing the default ports.

https://docs.netapp.com/us-en/occm/task_installing_linux.html#install-the-connector

Thanks again for reaching out and please let me know if any additional changes are needed.

**Comment by definitelynotsteve** [comment]
You. Are. Amazing.  Thank you, Ben!!
