### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by felix-melligan** [NetAppDocs/occm#797]
Page: [Installing the data broker on a Linux host](https://docs.netapp.com/us-en/occm/task_sync_installing_linux.html)

The link: this "NetApp-provided policy": https://s3.amazonaws.com/metadata.datafabric.io/docs/on_prem_iam_policy.json is broken.

**Comment by netapp-bcammett** [comment]
Hi Felix,

Thanks for letting me know. I sent a question off to the team to figure out where the policy went. 

Thanks again,
Ben
