### ISSUE TITLE
Need license limitation added to doc

### ISSUE THREAD

**Issue by mnicolase** [NetAppDocs/occm#802]
Page: [Cloud Manager documentation](https://docs.netapp.com/us-en/occm/index.html

Currently, there is no way to migrate a CVO node cluster to a capacity cluster. This must be added to documentation in order to inform customer willing to switch from a node license to a capacity license

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for reaching out. We do have a statement in the licensing overview section. See the last bullet below:

> ### Node-based licenses
> 
> - The previous generation BYOL for Cloud Volumes ONTAP.
> 
> - A node-based license is available for license renewals only.
> 
> - Each Cloud Volumes ONTAP system supports up to 368 TiB of capacity per license.
> 
> - Conversions to another licensing option isn’t supported.
> 
> If you want to transition to capacity-based licensing, you can purchase a license, deploy a new Cloud Volumes ONTAP system, and then replicate the data to that new system.

That text appears here in the Cloud Manager docs:
https://docs.netapp.com/us-en/occm/concept_licensing.html#node-based-licenses

And again in the Cloud Volumes ONTAP Release Notes:
https://docs.netapp.com/us-en/cloud-volumes-ontap/concept_licensing_9101.html#description-4

Does that match what you were looking for?

Thanks,
Ben

**Comment by mnicolase** [comment]
Good find Ben! For some reason I wasn't able to find that info.

Thank you very much for your time

Nick Maloizel
Cloud Technical Support Engineer 3
TSC / CSD
***@***.******@***.***>

[Graphical user interface, application  Description automatically generated]<https://www.youracclaim.com/badges/e825978e-5b73-4d1a-8e42-c7f19cea099d/public_url>[A close up of a sign  Description automatically ***@***.***<https://www.credly.com/badges/704b509d-30d9-476d-9740-476876f8711b>

My normal working hours are Monday to Friday, 7 a.m. - 4 p.m. EST (UTC−05:00).

For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP // * EMEA/Europe  00-800-44-638277 // * Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>.

Everyone in the NetApp Technical Support Center is committed to providing the highest level of customer satisfaction.  If you believe that the level of support can be improved, please contact my manager Theresa Boyle, at ***@***.******@***.***>.

[A picture containing bird  Description automatically generated]<https://www.netapp.com/us/index.aspx>

***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>
