### ISSUE TITLE
Step 4 Verbiage

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/occm#803]
Page: [Creating a Connector in Azure from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html)

Hello,  I believe that Step 4 on this page should read "Assign access to an Azure AD user, group, or service principal," and then before saying "Select User account" there should be a line that says "Click on "Select members."  Thanks!  

<img width="365" alt="Screenshot1" src="https://user-images.githubusercontent.com/90923881/149585811-ef2a38f3-491c-4456-854a-1450f8c38489.png">

**Comment by netapp-tonacki** [comment]
Hi alexmal98,  Thanks for your feedback; and for the handy screenshot.  We'll check on this and get back to you in the next couple days.

Thanks, Tom

**Comment by netapp-bcammett** [comment]
Hi Alex,

Thank you for submitting this issue. I looked at the Azure portal and they changed the screens around. I'll get the steps updated in the docs and let you know when the changes are complete.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Step 4 was updated in the following section to reflect the Azure portal UI changes:
https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html#granting-azure-permissions-using-a-service-principal

I also updated these same steps in other pages in the Cloud Manager docs.

Thanks again for reaching out to make us aware of the discrepancy.

Thanks again,
Ben
