### ISSUE TITLE
blob URL endpoint is needed for connector

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#813]
Page: [Networking requirements for the Connector](https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html)

On this page it looks like you only need 
*.blob.core.windows.net or https://hub.docker.com
for the linux host install

This endpoint is required in general as an endpoint for the connector.
It should be under: **Endpoints to manage resources in your public cloud environment**   as well.

**Comment by netapp-bcammett** [comment]
Hi Richard,

Thank you for submitting this feedback. I just copied you on an email thread to seek clarification because this goes against what I was told by the team. 

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The docs were updated to include *.blob.core.windows.net

Thanks again for your feedback.

Regards,
Ben
