### ISSUE TITLE
Germany Central should be Germany West Central

### ISSUE THREAD

**Issue by bnille** [NetAppDocs/occm#816]
Page: [Supported Azure Blob access tiers and regions](https://docs.netapp.com/us-en/occm/reference_azure_support.html)

Is the Region "Germany Central" really a Azure official usable region?
It should be "Germany West Central".

**Comment by netapp-tonacki** [comment]
Hi bnille,  Thanks for catching this.  Looks like "Germany Central" should be "Germany West Central".  Also looks like we have listed "Germany Northeast", and that should be "Germany North".  I'll update this in the docs shortly.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi bnille, I have fixed those 2 European Azure region names.  Thanks again for catching this.

Tom
