### ISSUE TITLE
Requesting update for High Availability Pairs pages in Cloud Manager docs

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/occm#821]
Page: [High-availability pairs in AWS](https://docs.netapp.com/us-en/occm/concept_ha.html)

Hi, can we get something added in the HA section for AWS, Azure and GCP that Cloud Manager disables actions like creating a new aggregate, volume, etc when the system is in takeover until giveback is complete?

Or is there somewhere in the docs that this is outlined?
I cant find it if so.

**Comment by netapp-bcammett** [comment]
Thank you for reaching out with this feedback. I will get the complete list of actions that are unavailable and I'll add it to the docs.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
From what I can see, the following actions are unavailable from Cloud Manager when an HA pair is degraded:

- Support registration
- Change License
- Change instance
- Write speed
- CIFS setup
- Configuration backups
- Set password
- Advanced allocation (manage disks and aggregates)

**Comment by netapp-bcammett** [comment]
I sent this list to the product team for verification. I'll add it to the documentation after that verification is complete.

**Comment by chuffster80** [comment]
Thanks a bunch Ben!

Best Regards,

Chris Huff
Technical Support Engineer
Technical Support Center, part of NetApp Customer Support Delivery

***@***.******@***.***>

My normal working hours are Monday – Friday, 7am. – 4pm. EST.
For technical assistance on a new or existing case, please call:
*US & Canada 888-4-NETAPP // *EMEA/Europe 00-800-44-638277 // *Asia/Pacific 800-8008-0800

[A picture containing drawing  Description automatically generated]<https://www.netapp.com/us/index.aspx>

***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>

***@***.***

**Comment by netapp-bcammett** [comment]
The actions mentioned in my comment above were added to the following page:
https://review.docs.netapp.com/us-en/occm_feb-2022-update3/concept-degraded-ha-pair.html

Thanks again for reaching out with this feedback.

Regards,
Ben
