### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/occm#825]
Page: [Tiering data from on-premises ONTAP clusters to Google Cloud Storage](https://docs.netapp.com/us-en/occm/task_tiering_onprem_gcp.html)

Hello,

In the "Steps" section under "Preparing Google Cloud Storage" the "enter the keys in Cloud Tiering" redirect link is not working. It shows 404.

**Comment by netapp-tonacki** [comment]
Hi Marco,  Thanks for your comment.  It is broken.  I've got a few doc changes going in shortly so I'll add that at the same time.

Thanks again for letting us know.   Tom

**Comment by netapp-tonacki** [comment]
Mi Marco,  I just removed that bad link because the link just went to the next section 2 lines below - so really not necessary.  It's all fixed now.  Thanks again.

Tom
