### ISSUE TITLE
Exchange unassigned node-based licenses

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#830]
Page: [Manage licenses for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_managing_licenses.html)

can we add the TB equivalent for node based license swaps instead of dollar value?
I guess this is 32TB for single node and 51TB for HA pair (not sure why its exactly the double of single node though).

**Comment by netapp-bcammett** [comment]
Thanks for submitting this question. I've reached out to our product team for clarification. I'll let you know what I hear.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The updated has been published:
https://docs.netapp.com/us-en/occm/task_managing_licenses.html#exchange-unassigned-node-based-licenses

Thanks again for providing this feedback.

Regards,
Ben
