### ISSUE TITLE
out of date ASUP requirements

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#834]
Page: [Setting up Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_setting_up_ontap_cloud.html)

The following statement seems to be outdated:
"The only required configuration step is to ensure that Cloud Volumes ONTAP has outbound internet connectivity. "

New requirements suggest that outbound internet access should be provided by a  PROXY or NAT GW:
https://docs.netapp.com/us-en/occm/reference_new_occm.html#connector-no-longer-supported-as-a-proxy
"You will need to provide AutoSupport connectivity through a NAT instance or your environment’s proxy services."

**Comment by netapp-bcammett** [comment]
The updated has been published:
https://docs.netapp.com/us-en/occm/task_setting_up_ontap_cloud.html

Thanks again for reaching out with your feedback.

Regards,
Ben
