### ISSUE TITLE
Adding information

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm#836]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/occm/concept_connectors.html)

Hello team, it would be nice also add AWS FSx for ONTAP in this phrase because a Connector is not required either: "A Connector is not required for Azure NetApp Files, Cloud Volumes Service, Cloud Sync, or Active IQ Digital Advisor."

Thank you.

**Comment by netapp-bcammett** [comment]
Hi Javier,

We can add FSx for ONTAP to that phrase, but we would need to add qualifying statements. Because while a Connector isn't required to create an FSx for ONTAP working environment, it is required for many management tasks:

> Using a Connector in AWS and Cloud Manager, you can create and manage volumes, replicate data, and integrate FSx for ONTAP with NetApp cloud services, such as Data Sense and Cloud Sync.

Thanks,
Ben

**Comment by jsuarezs** [comment]
I got the point Ben. I see now this is also specified before like: ```Amazon FSx for ONTAP advanced management features``` 

Many thanks btw for checking it.

**Comment by netapp-bcammett** [comment]
@jsuarezs, I'm publishing the following change, which I hope will clear up any confusion. What do yo think?

![image](https://user-images.githubusercontent.com/18287750/154103668-951315f4-e64b-4b6d-9349-95b24c9eaf17.png)
