### ISSUE TITLE
Scans of backfiles from on-prem

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#841]
Page: [Learn about Cloud Data Sense](https://docs.netapp.com/us-en/occm/concept_cloud_compliance.html)

I got to know that the below offering is no longer in use. The scanning of backup files are now counted.
can you please work with the product management and update the doc?

**Note**: When scanning backup files created from your on-prem ONTAP systems, the scanned data does not count against the capacity purchased in your PAYGO subscription or BYOL license.

**Comment by netapp-tonacki** [comment]
Hi Sabari,  I'll have a chat with the PM to get the full story and update the docs after that.  Thanks for letting me know.

Tom

**Comment by sabarig84** [comment]
Hi Tom,

Any update on this one pls?

**Comment by netapp-tonacki** [comment]
Hi Sabari,  I'm getting this and other related changes reviewed.  Should be ready in a couple days.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Sabari,  The Beta capability for using Cloud Data Sense to scan Cloud Backup "backup" files has been removed from Cloud Manager. This information has been removed from the Backup documentation for the Backup release that posted yesterday. The documentation for Data Sense will reflect that change very soon when the new Data Sense release is posted.

Thanks, Tom

**Comment by sabarig84** [comment]
Hi Tom,

thanks for getting back, its still a little confusing. the CM release notes say "The capability to use Cloud Data Sense to scan your backup files has been removed in this release". does this mean we cannot use cloud data sense to scan those object store targets at all? or is it still possible to do it by selecting the object store. what i was expecting as a doc update is, the previously offered free capability to scan the back files created by CBS has been discontinued or something in similar lines.
