### ISSUE TITLE
Clarify firewall rules for on-prem connectors

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#842]
Page: [Networking requirements for the Connector](https://docs.netapp.com/us-en/occm/reference_networking_cloud_manager.html)

For the "Ports for the on-prem Connector" section, the details need to match what is provided in the similar "Rules for Connector in <cloud>" sections; i.e. a detailed list of ports broken up into inbound and outbound port requirements.  As currently written it is not clear if these are all inbound ports only, or a combination of inbound and outbound ports.  If inbound, the source needs to be identified, i.e. port 3306 is listed for Cloud Manager database but what is the source system(s) that needs to access this port?

**Comment by netapp-bcammett** [comment]
Mike,

Thanks for catching this oversight. I just sent a message to the product team to get more information.

**Comment by netapp-bcammett** [comment]
I have the full details of the ports and I wrote up a final draft. I'm sending it to the product team for verification and then I should be publishing the updates in a few days.

In short: it's just ports 80 and 443 for inbound communication. The other ports that are currently listed in the docs are used by internal components only (no inbound or outbound communication from those ports).

**Comment by netapp-bcammett** [comment]
I published the doc updates to show just the two internal ports.

Thanks again for reaching out.

Regards,
Ben
