### ISSUE TITLE
Missing Outbound firewall rules for CVO

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/occm#843]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

Hello, the doc states that "Cloud Volumes ONTAP requires outbound internet access to send messages to NetApp AutoSupport, which proactively monitors the health of your storage." but in the advanced outbound rules for CVO it is not specified the port 443 that will allow ASUP.

Would it be better to indicate that port in the table ? I know that it is not mandatory to have the CVO working but it is mandatory if you want to send ASUP.

**Comment by netapp-bcammett** [comment]
Hi Marco,

Thank you for submitting this request. I went ahead and added HTTPS and HTTP to the list of advanced outbound rules. I added it to the pages for AWS, Azure, and Google Cloud.

Thanks again for reaching out.

Regards,
Ben
