### ISSUE TITLE
Overage billing is now started?

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/occm#845]
Page: [Cloud Volumes ONTAP licensing](https://docs.netapp.com/us-en/occm/concept_licensing.html)

In my understanding, overage billing does not work. but mu customer find below in the document.
> If you exceed your BYOL capacity or if your license expires, you’ll be charged for overages at the hourly rate based on your marketplace subscription.

According to this text, it seems that overagebilling has been started, is that correct?
If so, could you please consider to add notes that when overage billing has been started?

Best regards,

**Comment by netapp-bcammett** [comment]
Just wanted to let you know that I'm still waiting on an official answer and will update this issue as soon as I have it.

**Comment by netapp-bcammett** [comment]
Closing after internal communication with Masafumi.
