### ISSUE TITLE
Missing encryption permission

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#846]
Page: [Backing up on-premises ONTAP data to Amazon S3](https://docs.netapp.com/us-en/occm/task_backup_onprem_to_aws.html)

Preparing Amazon S3 for backups
This list for the S3 bucket permissions is missing:
"s3:PutEncryptionConfiguration"

**Comment by netapp-tonacki** [comment]
Hi Richard,  Thanks for letting me know.  I will add this permission today.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hey Richard,  I checked with the team and they said we need "s3:PutBucketencryption" (not "s3:PutEncryptionConfiguration"), so I added that to the docs.  If you want to discuss, let me know thru email and I can connect you with the person I spoke with.

Thanks for bring this to our attention.    Tom
