### ISSUE TITLE
Clarification on Outbound Internet Access Endpoints

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#847]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

IHAC looking for clarification for required Outbound Internet Endpoints.  The following is listed on this page:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/33675510/155203523-92104089-4c85-4024-813a-4f290987e14c.png">

`"https://cloudmanagerinfraprod.azurecr.io" and *.blob.core.windows.net are listed in the same row.  Are these two separate URLs?  If so, should the 2nd entry actually be https://*.blob.core.windows.net?`

**Comment by netapp-bcammett** [comment]
Mike,

Yes, these are two separate URLs just like you noted. I'm pushing an update right now to help avoid any confusion.

**Comment by netapp-bcammett** [comment]
Mike,

The doc updates are complete. Can you please take a look and let me know if the change helps clear up the confusion?

Thanks,
Ben

**Comment by mimitche** [comment]
The updates look great; thanks Ben!
