### ISSUE TITLE
Clarify that capacity license can be used with multiple clouds

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/occm#849]
Page: [Cloud Volumes ONTAP licensing](https://docs.netapp.com/us-en/occm/concept_licensing.html)

Could you add a comment clarifying that a BYOL capacity license purchased from NetApp can be used to deploy CVOs in AWS, Azure and GCP, ie the capacity license is not restricted to deploying CVOs in a single cloud, thank you!

**Comment by netapp-bcammett** [comment]
Hi Neil,

Great suggestion. I will update the page in a bit and let you know when it's ready.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Neil,

The doc updates are complete. I made two changes.

First, I updated the Freemium description:

> You can use up to 10 Cloud Volumes ONTAP systems with the Freemium offering per NetApp account, **in any cloud provider**.

Second, I updated the capacity-based BYOL description like you requested:

> A license (BYOL) purchased from NetApp **that can be used to deploy Cloud Volumes ONTAP in any cloud provider**.
**The license is not restricted to a single cloud provider**.

Thank you again for reaching out and please let me know if you have any additional feedback.

Thanks,
Ben
