### ISSUE TITLE
Remove Time Synchronization Requirement for Azure resources

### ISSUE THREAD

**Issue by mark-beaupre** [NetAppDocs/occm#852]
Page: [Prerequisites to create Connector and enable SnapCenter Service](https://docs.netapp.com/us-en/occm/prerequisites-azure-connector-snapcenter-service.html)

Azure VMs and resources are configured to use time.windows.com as the ntp time source automatically. There is no need to specify ntp.ubuntu.com as the time source for Azure virtual machines. 

Please remove the following line from the network rules in Step 1 of the Firewall Configuration

FQDN - ntp.ubuntu.com:123 | UDP | 123 | Required for time synchronization in Azure virtual machines.

Thanks!
Mark

**Comment by netapp-soumikd** [comment]
Thank you for your comment. I am discussing with Engineering and will update soon.

**Comment by netapp-soumikd** [comment]
I discussed with Engineering, and he says that this is required for Azure AKS. 
It is also specified in the Azure doc: Restrict egress traffic in [Azure Kubernetes Service (AKS) - Azure Kubernetes Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-outbound-network-rules-and-fqdns-for-aks-clusters)

**Comment by netapp-soumikd** [comment]
I assume my response was satisfactory. Thus, closing this issue.

If you have any further queries, feel free to open an issue.
