### ISSUE TITLE
The link is 404

### ISSUE THREAD

**Issue by Shihao1995** [NetAppDocs/occm#854]
In this Page: [Disks and aggregates](https://docs.netapp.com/us-en/occm/concept_storage.html)
The link([Microsoft Azure documentation: Introduction to Microsoft Azure Storage](https://azure.microsoft.com/documentation/articles/storage-introduction/)) shows 404 error.
Maybe need to correct it.

**Comment by netapp-bcammett** [comment]
Thank you for making me aware of this issue. I've found the correct URL (looks like it changed on us) and I'll be updating it later today.

I'll let you know when the change is complete.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
The link has been fixed. Thanks again!
