### ISSUE TITLE
High Write Speed across AZs is more resilient

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/occm#858]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

From Chad Morganstern and others we have discovered that there is more resiliency with high write speed when the HA pair is across AZs. Honestly I think that is a good tradeoff as most customers shy away from high write speed due to losing 2 CPs.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this feedback. I'll touch base with folks on the team to see how we want to communicate this in the docs.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
@MrObvious

I discussed with the lead developer on this feature and here's what we propose for the documentation:

> If you plan to enable high write speed on an HA pair in AWS, you should understand the difference in protection levels between a multiple Availability Zone (AZ) deployment and a single AZ deployment. Deploying an HA pair across multiple AZs provides a higher level of protection in case of an AZ outage. This higher level of protection can help to reduce the chance of data loss.

Please let me know what you think.

Thanks,
Ben

**Comment by MrObvious** [comment]
Ben,

True. In my experience however, it isn't as obvious. I think because it's obfuscated by the layers of ONTAP it isn't as obvious.

**Comment by MrObvious** [comment]
Sorry, I guess I should say if dev wants to update they can, but otherwise if not that's fine too. I think everyone knows the difference, but it is a fair statement that mutli-AZ HA CVO definitely has more reliability with LDM than not.

**Comment by netapp-bcammett** [comment]
@MrObvious, here's an update with a more direct statement at the end:

> If you plan to enable high write speed on an HA pair in AWS, you should understand the difference in protection levels between a multiple Availability Zone (AZ) deployment and a single AZ deployment. **Deploying an HA pair across multiple AZs provides more resiliency and can help to mitigate the chance of data loss.**

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Great. Glad to hear that. I updated the docs with this new section.
https://docs.netapp.com/us-en/occm/concept_write_speed.html#high-write-speed-with-an-ha-pair-in-aws

Thanks again for reaching out.
