### ISSUE TITLE
Wrong Cloud Manager SaaS ID listed.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#860]
Page: [Set up permissions for FSx for ONTAP](https://docs.netapp.com/us-en/occm/task_setting_up_permissions_fsx.html)

The ID of the Cloud Manager SaaS: 733004784675  appears to be incorrect.

When following these steps, at the last step I got the error in this image which indicated that it was attempting with ID of the Cloud Manager SaaS as 952013314444:

![image](https://user-images.githubusercontent.com/519212/156795263-63907851-bbe1-4bac-a891-b2149a587cf5.png)

When I put that value "952013314444" into the setup of the Trusted Entity type in my AWS account, then I was able to successfully add the Credential.

**Comment by netapp-bcammett** [comment]
I fixed the account ID to 952013314444.

Thank you for catching this, Richard!
