### ISSUE TITLE
Misleading statement you will need AWS Key/Secret

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#861]
Page: [Get started with Amazon FSx for ONTAP](https://docs.netapp.com/us-en/occm/task_getting_started_fsx.html)

Now that we support ARN / Assume Role for credentials, this statement is misleading:
"You will need an AWS access key and secret key"

The link right after goes through process using Assume Role.

**Comment by juliantap** [comment]
Thank you, @nichollri! I thought I had caught all the references, but it seems I missed one. I'll remove this and update. Thanks!

**Comment by juliantap** [comment]
Thanks again, @nichollri. This correction has been merged with #865.
