### ISSUE TITLE
GCP connector credentials

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#870]
Page: [Creating a Connector in GCP from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html)

During the GCP connector creation it doesn't ask for credentials (user name/password). can we explain in the docs, if we dont know that, how to login to connector via SSH? can that be explained in docs pls?

**Comment by netapp-bcammett** [comment]
Hi Sabari,

Thanks for reaching out. I just sent a question off to the product team for clarification. I'll let you know what I hear.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I added a section in the managing Connectors page about connecting to the Linux VM:
https://docs.netapp.com/us-en/occm/task_managing_connectors.html#connect-to-the-linux-vm

Thanks again for reaching out.

Regards,
Ben
