### ISSUE TITLE
Install patches in connector operating system

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#871]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/occm/concept_connectors.html)

during security scans if there are any vulnerabilities listed against the OS in which the connector runs,  are we allowed to patch the operating system in which the connector runs? is this supported?

Also we can see that there shouldnt be any 3rd party agents or monitoring tools installed on the connector OS. can this be called out in the doc as well?

**Comment by sabarig84** [comment]
Sorry, i found the answer for the first part here .. https://docs.netapp.com/us-en/occm/task_managing_connectors.html#apply-security-updates

Would it possible to add this KB in an appropriate place as well? https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)/Are_3rd_party_agents_or_monitoring_tools_supported_on_cvo_or_connector_vm%3F

**Comment by netapp-bcammett** [comment]
Hi Sabari,

Yes, I'll add the information from the KB to the docs. I'll let you know when this is done.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I added the limitation about 3rd party agents or monitoring tools.
https://docs.netapp.com/us-en/occm/concept_connectors.html#3rd-party-agents-and-extensions

Thanks again for submitting this feedback.

Regards,
Ben
