### ISSUE TITLE
HA pair IP addresses

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/occm#872]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

In the doc we say that we need 15 or 16 IP addresses for an HA pair but the sum of the addresses required for the 4 VPCs is 14 or 15.

Would it be possible to fix that ?

**Comment by netapp-bcammett** [comment]
Hi Marco,

Yes, I will fix that today. Thank you for submitting this issue.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Fixed!

> HA pair: 14 or 15 private IP addresses

Thanks again,
Ben
