### ISSUE TITLE
Typo in security update command

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#875]
Page: [Managing existing Connectors](https://docs.netapp.com/us-en/occm/task_managing_connectors.html)

In the "Apply security updates" section

`yum -y update –security`
should be
`yum -y update --security`

**Comment by netapp-bcammett** [comment]
Mike,

What timing--I'm editing this page right now. I've added the extra - and will publish shortly.

Thanks as always!

**Comment by netapp-bcammett** [comment]
The typo has been fixed.
https://docs.netapp.com/us-en/occm/task_managing_connectors.html#apply-security-updates

Thanks,
Ben
