### ISSUE TITLE
Shared VPC requirements 

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/occm#879]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/occm/reference_networking_gcp.html)

Hello, would it be possible to add, in the shared VPCs requirements section, the link to this table: https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html#shared-vpc-permissions

In the section we say that “The only requirement when using a shared VPC is to provide the Compute Network User role to the Connector service account” but I think it does not explain all the requirements as per the table.

**Comment by netapp-bcammett** [comment]
@melatsg, yes, I will make that change. Thank you for submitting this feedback.

**Comment by netapp-bcammett** [comment]
Marco,

I added a link to the table that was just updated.

Thanks again for your feedback.

Regards,
Ben
