### ISSUE TITLE
Add details to the Shared VPC permissions section

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/occm#880]
Page: [Creating a Connector in GCP from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html)

I have 2 suggestions regarding the “Shared VPC permissions” section:

1)Would it be possible to add the details on why we need the “deploymentmanager.editor” role on the host project? 
The note 1 gives me the hint that it is required to create and delete firewall rules but I don’t find it very clear, in particular checking the GCP role permissions https://cloud.google.com/deployment-manager/docs/access-control#roles

2)Would it be possible to specify that the firewall.create and firewall.delete permissions mentioned in note 2 are referring to the “Cloud Manager service account” permissions you can find in the yaml file and that those permissions are used to create the firewall rules in the service project and not in the host project?
Reading the doc I find difficult to understand that the note 2 is referring only to the service project firewall rules because I can interpret that the firewall.create and firewall.delete permissions are contained in the roles “compute.networkUser” or “deploymentmanager.editor” that we say are needed on the host project. Only if I check the GCP role permissions I can find that those roles do not have those specific permissions.

Maybe it would be easier to understand also adding the note reference near the specific element.
For example: deploymentmanager.editor^1 (I can't format as superscript)

**Comment by netapp-bcammett** [comment]
@melatsg, thank you for reaching out with this feedback.

@felix-melligan, as you provided the content for this section, would you mind responding to Marco's feedback in order to confirm the changes that we need to make?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@melatsg, Felix updated the section to address your feedback. Please take a look and let us know if you have any additional feedback. https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html#shared-vpc-permissions

Thanks as always!

Regards,
Ben
