### ISSUE TITLE
Additional Details Needed for Mediator Instance

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#886]
Page: [High-availability pairs in Google Cloud Platform](https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html)

IHAC that needs additional details of the mediator instance documented in order to get security approval for deployment of CVO in GCP.  Currently the following is stated for the mediator:

```
A mediator instance that provides a communication channel between the nodes to assist in storage takeover and giveback processes.

The mediator runs the Linux operating system on a f1-micro instance and uses two standard persistent disks that are 10 GB each.
```

Can the additional following details be added about the mediator instance:

1. What is the specific Linux flavor/version that is deployed?
2. How does this mediator instance get patched/upgraded if needed?
3. Does the administrator deploying CVO HA in their environment get root access to this instance?
4. Can 3rd party security agents be installed on this instance?

**Comment by netapp-bcammett** [comment]
Hi Mike,

I'm checking with the product team to get answers to a few of these. After that, I'll update the docs with these details. 

Thanks,
Ben
