### ISSUE TITLE
BYOL conversion

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#888]
Page: [License management for node-based BYOL](https://docs.netapp.com/us-en/occm/concept_license_management.html)
Hello Team,

Requesting an update on the documentation in order to emphasize that other licensing solutions cannot be converted to BYOL.

**Comment by netapp-bcammett** [comment]
Hey there,

I can't access that JIRA. Can you please reach out to me internally with the details? I'm not entirely sure what you mean by "other licensing solutions."

If this is in reference to by-node licensing, the licensing overview page does mention that conversions are not supported: https://docs.netapp.com/us-en/occm/concept_licensing.html#node-based-licensing

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Gabor,

Based on our internal discussions, a new section was added here:
https://docs.netapp.com/us-en/occm/concept_licensing.html#license-conversions

Thanks again for this feedback.

Regards,
Ben

**Comment by laagabi** [comment]
Looks awesome! Thank you Ben for your help! 😊

BR,
Gabor.
