### ISSUE TITLE
Connector for digital wallet

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/occm#897]
Page: [Learn about Connectors](https://docs.netapp.com/us-en/occm/concept_connectors.html)

can we please clarify if a connector is needed to use digital wallet? this has come up few times....

**Comment by sabarig84** [comment]
thanks Ben. If we have a CVO (whether its node based or capacity based) then we need a connector. How about cloud tiering which was previously fabricpool? if you could confirm that, that would be great.

**Comment by sabarig84** [comment]
Iam talking about customers who are or will be using this new license.
https://docs.netapp.com/us-en/occm/task_licensing_cloud_tiering.html#new-cloud-tiering-byol-licensing-starting-august-21-2021

**Comment by sabarig84** [comment]
to use that licensing they will need to use DW. so will that need a connector? :). sorry if i had framed my previous question in a confusing way.

**Comment by netapp-bcammett** [comment]
A Cloud Tiering license is a "Data Services License" that you manage in the Digital Wallet. So yes, you can add this type of license to the Digital Wallet without a Connector.

**Comment by netapp-bcammett** [comment]
I added the information to the docs:
https://docs.netapp.com/us-en/occm/concept_connectors.html#when-a-connector-is-required

Thanks again!
