### ISSUE TITLE
broken hyperlink

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#898]
Page: [Deploy Cloud Data Sense on a Linux host that has internet access](https://docs.netapp.com/us-en/occm/task-deploy-compliance-onprem.html)

Hello Team,

The hyperlinks in these texts appear to be broken. Clicking them will not take us to the next page (or the section on the same page)
![2022-03-25 13_19_19-Window](https://user-images.githubusercontent.com/80273701/160122730-ce28dd98-04ed-4872-a03a-d0be141c27b9.png)

**Comment by netapp-tonacki** [comment]
Hi Gabor,  Thanks for catching this.  I'll fix this and let you know when the updated version is posted.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi,  The fixed version is posted now.  Thanks again for flagging this issue.

Tom

**Comment by laagabi** [comment]
Thanks Tom! Appreciate the help!

Gabor.
