### ISSUE TITLE
CLI steps to create Storage VMs should includes vserver add-aggregate -vserver (svm) -aggregate (aggr)

### ISSUE THREAD

**Issue by hiho-hiho** [NetAppDocs/occm#902]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/task_managing_svms_aws.html)

Now SVMs created by CLI steps don't have aggr-list.
If creating volumes using GUI after creating SVMs using CLI,
Cloud Manager sends /applications/applications API to CVO and it does not include aggregate parameter.
As a result, API fails with no suitable aggregate.

After adding aggr-list to SVMs , creating volumes using GUI works.
So it seems that CLI steps should include vserver add-aggregate -vserver (svm) -aggregate (aggr).

**Comment by hiho-hiho** [comment]
Hi Ben,

Sorry for the late reply.
I have no problem with what you have presented.

Thanks,
Hisaki

**Comment by netapp-bcammett** [comment]
I updated the docs with the steps that I mentioned above.

Thanks again for submitting this feedback!

Regards,
Ben
