### ISSUE TITLE
mis-edited sentence

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/occm#903]
Page: [What’s new in Cloud Manager 3.9](https://docs.netapp.com/us-en/occm/reference_new_occm.html)

Section jump is: https://docs.netapp.com/us-en/occm/reference_new_occm.html#cloud-compliance-enhancements-5

I know this section is ancient (jan 2021) but I noticed it and couldn't not report it. :)

> The "Policies" feature **now allows you can create** your own custom Policies that provide results for searches specific to your organization.

**Comment by netapp-tonacki** [comment]
Thanks Megan.  I'm only pulling in 1yr of new features to the new repos, so this will be moot very shortly. 

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I'm going to close it since the new repos will be live in 2 days and this is a minor and old typo.
