### ISSUE TITLE
wrong role mentioned in the "Assign the application to the role" -section

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/occm#908]
Page: [Creating a Connector in Azure from Cloud Manager](https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html)

Hi Team,

I think there is a mistake here. In Step 3 "Use the JSON file to create a custom role in Azure" we create the "Azure SetupAsService" role.
In Step 4 we say to add the "Cloud Manager Operator" role to the application, which I think is wrong.

![image](https://user-images.githubusercontent.com/80273701/160910015-89c89323-63df-47ef-8b6a-553837984c5c.png)

**Comment by netapp-bcammett** [comment]
Fixed! Thank you!
