### ISSUE TITLE
NTP server option does not exist after setup 

### ISSUE THREAD

**Issue by zhimingCN** [NetAppDocs/occm#912]
Page: [Managing existing storage](https://docs.netapp.com/us-en/occm/task_managing_storage.html)

Hi Team,

Regarding the NTP option. It only can be checked while setting up the environment.
after setup NTP server option disappeared from GUI, need to clarify this on this page.

https://docs.netapp.com/us-en/occm/task_setting_up_ontap_cloud.html (NTP server can be modified with API or setup GUI only.)
>Specify an NTP server using the Cloud Manager API or from the user interface when you set up a CIFS server.

For your reference, I have confirmed this with support team.
https://jira.ngage.netapp.com/browse/CDS-4332

Modifying the CIFS server
NTP Server 
Select Use Active Directory Domain to configure an NTP server using the Active Directory DNS. If you need to configure an NTP server using a different address, then you should use the API. See the [Cloud Manager automation docs](https://docs.netapp.com/us-en/cloud-manager-automation/index.html) for details.

**Comment by netapp-bcammett** [comment]
@zhimingCN 
I confirmed that specifying an NTP server is possible only when creating the CIFS server. You can create the CIFS server during working environment creation or any time after. But once you create the CIFS server, you can no longer specify an NTP server.

I'm in the process of updating the docs to reflect this behavior.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
The documentation updates are complete. Thanks again for submitting this issue.

Here's commit that fixes this issue:
https://github.com/NetAppDocs/occm/commit/b7a0afb8cec1a12ca6b299ddc61098a645cb81af

Regards,
Ben

**Comment by zhimingCN** [comment]
Great, thanks
