### ISSUE TITLE
Add step to upgrade procedures for Dark Site upgrades

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/occm#920]
Page: [Deploy Cloud Data Sense on prem without internet access](https://docs.netapp.com/us-en/occm/task-deploy-compliance-dark-site.html)

Please add the following step to docs as it is required to upgrade:

After step 3 in the Darksite upgrade process, please add the following step:

4. Unzip the installation file on the host machine, for example:
      Example: tar -xzf cc_onprem_installer_1.10.0.tar.gz

**Comment by netapp-tonacki** [comment]
Hi David,  Thanks for the comment.  I see that step in the Install procedure, but you are correct I missed it for the Upgrade procedure.  I'll update that soon and let you know.

Thanks, Tom

**Comment by virtualhawk** [comment]
Thanks Tom!

Thanks,

David Hawkins
Professional Services Consultant
Global Services Solutions Center

NetApp
+1 330.892.7057 Direct Phone
***@***.******@***.***>

Upcoming Out of the office: None

From: Tom Onacki ***@***.***>
Date: Wednesday, April 6, 2022 at 9:34 AM
To: NetAppDocs/occm ***@***.***>
Cc: Hawkins, David ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/occm] Add step to upgrade procedures for Dark Site upgrades (Issue #920)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi David, Thanks for the comment. I see that step in the Install procedure, but you are correct I missed it for the Upgrade procedure. I'll update that soon and let you know.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi David,  I was making another change in the Data Sense docs, so I made this one at the same time. [Take a look here](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-dark-site.html#upgrade-data-sense-software) to see if there is anything else.

Thanks again for bringing this to our attention.

Thanks, Tom
