### ISSUE TITLE
Add some detail to multi-zone HA examples

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/occm#97]
Page: [Networking requirements for Cloud Volumes ONTAP in AWS](https://docs.netapp.com/us-en/occm/reference_networking_aws.html#a-vpc-with-public-and-private-subnets-and-a-nat-device)

It would be helpful if figures on this page had a bit more IP addresses and other network details in them.
https://docs.netapp.com/us-en/occm/reference_networking_aws.html#a-vpc-with-public-and-private-subnets-and-a-nat-device

Schematics on that page and other related pages (e.g. https://docs.netapp.com/us-en/occm/concept_ha.html#data-access) are clear and uncluttered, but it's not easy to imagine how IPs, netmasks and routes might need to be set up in some of those examples. 

In order to mark IP addresses and settings done in OCCM/CVO separately, maybe have those in a different color so that the reader can tell which settings are done in OCCM/CVO and which separately?

**Comment by netapp-bcammett** [comment]
@scaleoutsean -- Thank you for your feedback. Just to be clear, your request centers around identifying the networking information (IPs, netmasks, and routes) that the user must set up and what Cloud Manager automatically sets up for users?

**Comment by scaleoutsean** [comment]
Yes. After submitting the above issue I came across a good example [here](https://kubernetes.io/docs/getting-started-guides/windows/#upstream-l3-routing-topology)
In addition to the level of detail, the colors of different parts informs the reader what happens where and who's in charge of what - seems very easy to understand which part should be planned and executed by whom.

Maybe that's too much detail and could be moved to a separate "tutorial"-like page or completely different site where we'd like to share this level of detail, I don't have a strong opinion on that.

**Comment by netapp-bcammett** [comment]
Information about IP addressing was added through issue #587.
